const words={
it:['Controlla risposta aziendale','Verifica in corso…','Approvato: la risposta riguarda questa versione.','L’azienda chiede delle modifiche.','In attesa della verifica aziendale.','Il documento è cambiato: la risposta precedente non vale per questa versione.','Le regole aziendali sono cambiate: serve una nuova verifica.'],
en:['Check company response','Checking…','Approved: this decision applies to this version.','Your company requests changes.','Awaiting company review.','The report changed: the previous decision does not apply to this version.','Company rules changed: a new review is needed.'],
de:['Unternehmensantwort prüfen','Wird geprüft…','Genehmigt: Die Entscheidung gilt für diese Version.','Das Unternehmen bittet um Änderungen.','Unternehmensprüfung ausstehend.','Bericht geändert: Die frühere Entscheidung gilt nicht für diese Version.','Unternehmensregeln geändert: Eine neue Prüfung ist nötig.'],
fr:['Vérifier la réponse de l’entreprise','Vérification…','Approuvé : cette décision concerne cette version.','L’entreprise demande des modifications.','En attente de vérification par l’entreprise.','Le rapport a changé : la décision précédente ne concerne pas cette version.','Les règles ont changé : une nouvelle vérification est nécessaire.'],
es:['Consultar respuesta de la empresa','Consultando…','Aprobado: la decisión corresponde a esta versión.','La empresa solicita cambios.','Pendiente de revisión de la empresa.','El informe cambió: la decisión anterior no corresponde a esta versión.','Las reglas cambiaron: hace falta otra revisión.'],
nl:['Bedrijfsreactie bekijken','Controleren…','Goedgekeurd: dit besluit geldt voor deze versie.','Je bedrijf vraagt wijzigingen.','Wacht op bedrijfscontrole.','Het rapport is gewijzigd: het eerdere besluit geldt niet voor deze versie.','Bedrijfsregels gewijzigd: een nieuwe controle is nodig.'],
pt:['Consultar resposta da empresa','A consultar…','Aprovado: a decisão aplica-se a esta versão.','A empresa pede alterações.','Aguarda revisão da empresa.','O relatório mudou: a decisão anterior não se aplica a esta versão.','As regras mudaram: é necessária uma nova revisão.'],
};
export const companyStatusCopy=(lang,key)=>(words[lang]||words.en)[typeof key==='number'?key:({approved:2,changes_requested:3,pending:4,changed:5,policy:6})[key]];
