const copy={
 it:['Invia all’azienda','Invierai una copia del resoconto e dei suoi allegati alla tua azienda.','Invio in corso…','Ricevuto dall’azienda. In attesa di verifica, non ancora approvato.','Non ho ricevuto conferma. I dati restano qui: puoi riprovare senza duplicare l’invio.','Accedi di nuovo allo spazio aziendale e riprova.','Gli allegati superano il limite attuale di invio (256 KiB). I dati sono conservati.','Le regole aziendali sono cambiate. Il resoconto va aggiornato prima dell’invio.','Il resoconto è cambiato. Riaprilo prima di inviare.','Controlla i dati del resoconto prima di riprovare.','Chiudi'],
 en:['Send to company','A copy of this report and its attachments will be sent to your company.','Sending…','Received by your company. Awaiting review, not approved yet.','No confirmation received. Your data is still here: retry without duplicating the submission.','Sign in to your company workspace again and retry.','Attachments exceed the current upload limit (256 KiB). Your data is retained.','Company rules changed. Update the report before sending.','The report changed. Reopen it before sending.','Check the report data before retrying.','Close'],
 de:['An Unternehmen senden','Eine Kopie des Berichts samt Belegen wird an dein Unternehmen gesendet.','Wird gesendet…','Vom Unternehmen empfangen. Prüfung ausstehend, noch nicht genehmigt.','Keine Bestätigung erhalten. Deine Daten bleiben hier: erneut senden ohne Duplikat.','Melde dich erneut im Unternehmensbereich an.','Belege überschreiten das aktuelle Limit (256 KiB). Deine Daten bleiben erhalten.','Unternehmensregeln geändert. Aktualisiere den Bericht vor dem Senden.','Bericht geändert. Öffne ihn vor dem Senden erneut.','Prüfe die Berichtsdaten vor einem neuen Versuch.','Schließen'],
 fr:['Envoyer à l’entreprise','Une copie du rapport et de ses justificatifs sera envoyée à votre entreprise.','Envoi…','Reçu par l’entreprise. En attente de vérification, pas encore approuvé.','Aucune confirmation reçue. Vos données restent ici : réessayez sans doublon.','Reconnectez-vous à votre espace entreprise.','Les pièces dépassent la limite actuelle (256 KiB). Vos données sont conservées.','Les règles ont changé. Actualisez le rapport avant l’envoi.','Le rapport a changé. Rouvrez-le avant l’envoi.','Vérifiez les données avant de réessayer.','Fermer'],
 es:['Enviar a la empresa','Se enviará una copia del informe y sus adjuntos a tu empresa.','Enviando…','Recibido por la empresa. Pendiente de revisión, aún no aprobado.','Sin confirmación. Tus datos siguen aquí: reintenta sin duplicar el envío.','Vuelve a acceder al espacio de empresa.','Los adjuntos superan el límite actual (256 KiB). Tus datos se conservan.','Las reglas cambiaron. Actualiza el informe antes de enviarlo.','El informe cambió. Ábrelo de nuevo antes de enviarlo.','Revisa los datos antes de reintentar.','Cerrar'],
 nl:['Naar bedrijf sturen','Een kopie van het rapport en de bijlagen wordt naar je bedrijf gestuurd.','Versturen…','Ontvangen door je bedrijf. Wacht op controle, nog niet goedgekeurd.','Geen bevestiging. Je gegevens blijven hier: probeer opnieuw zonder dubbel in te dienen.','Meld je opnieuw aan bij je bedrijfsruimte.','Bijlagen overschrijden de huidige limiet (256 KiB). Je gegevens blijven bewaard.','Bedrijfsregels gewijzigd. Werk het rapport bij voor verzending.','Rapport gewijzigd. Open het opnieuw voor verzending.','Controleer de gegevens en probeer opnieuw.','Sluiten'],
 pt:['Enviar à empresa','Uma cópia do relatório e dos anexos será enviada à sua empresa.','A enviar…','Recebido pela empresa. Aguarda revisão, ainda não aprovado.','Sem confirmação. Os dados continuam aqui: tente novamente sem duplicar o envio.','Volte a entrar no espaço empresarial.','Os anexos excedem o limite atual (256 KiB). Os dados são conservados.','As regras mudaram. Atualize o relatório antes de enviar.','O relatório mudou. Abra-o novamente antes de enviar.','Verifique os dados antes de tentar novamente.','Fechar'],
};
export const companySubmitCopy=(lang,key)=>(copy[lang]||copy.en)[key];
export const companySubmitError=(lang,code)=>companySubmitCopy(lang,({network:4,access:5,large:6,policy:7,changed:8,invalid:9})[code]??9);
