const rows={
it:['Documenti e ricevute','Aggiungi gli originali, poi salva il pacchetto. I file restano qui solo finché questa schermata è aperta. Non è conservazione fiscale né verifica di accettazione.','Aggiungi documento','Aggiungi ricevuta','Apri pacchetto','Salva pacchetto','Scarica originale','Integrità verificata. Autenticità ed esito fiscale non verificati.','File non valido, troppo grande o riferito a un’altra fattura.','Scegli prima il documento a cui appartiene la ricevuta.','Documento per la ricevuta','Nessun file aggiunto.','Operazione in corso…'],
en:['Documents and receipts','Add originals, then save the package. Files remain here only while this screen is open. This is not legal preservation or acceptance verification.','Add document','Add receipt','Open package','Save package','Download original','Integrity verified. Authenticity and tax outcome not verified.','Invalid or oversized file, or a different invoice.','First select the document this receipt belongs to.','Document for the receipt','No files added.','Working…'],
de:['Dokumente und Belege','Originale hinzufügen und Paket speichern. Dateien bleiben nur bei geöffnetem Fenster hier. Keine rechtskonforme Archivierung oder Annahmeprüfung.','Dokument hinzufügen','Beleg hinzufügen','Paket öffnen','Paket speichern','Original herunterladen','Integrität geprüft. Echtheit und Steuerergebnis ungeprüft.','Ungültige oder zu große Datei oder andere Rechnung.','Zuerst das zugehörige Dokument wählen.','Dokument zum Beleg','Keine Dateien hinzugefügt.','Wird bearbeitet…'],
fr:['Documents et reçus','Ajoutez les originaux puis enregistrez le paquet. Les fichiers restent ici uniquement pendant l’ouverture de cet écran. Ni archivage légal ni vérification d’acceptation.','Ajouter un document','Ajouter un reçu','Ouvrir un paquet','Enregistrer le paquet','Télécharger l’original','Intégrité vérifiée. Authenticité et résultat fiscal non vérifiés.','Fichier invalide, trop volumineux ou autre facture.','Choisissez d’abord le document associé au reçu.','Document du reçu','Aucun fichier ajouté.','En cours…'],
es:['Documentos y justificantes','Añade originales y guarda el paquete. Los archivos permanecen aquí solo mientras esta pantalla está abierta. No es conservación legal ni verificación de aceptación.','Añadir documento','Añadir justificante','Abrir paquete','Guardar paquete','Descargar original','Integridad verificada. Autenticidad y resultado fiscal sin verificar.','Archivo inválido, demasiado grande o de otra factura.','Elige primero el documento del justificante.','Documento del justificante','No hay archivos.','Procesando…'],
nl:['Documenten en ontvangstbewijzen','Voeg originelen toe en sla het pakket op. Bestanden blijven alleen hier zolang dit scherm open is. Geen wettelijke bewaring of controle van aanvaarding.','Document toevoegen','Bewijs toevoegen','Pakket openen','Pakket opslaan','Origineel downloaden','Integriteit gecontroleerd. Echtheid en fiscaal resultaat niet gecontroleerd.','Ongeldig of te groot bestand of andere factuur.','Kies eerst het bijbehorende document.','Document voor het bewijs','Geen bestanden toegevoegd.','Bezig…'],
pt:['Documentos e comprovativos','Adicione originais e guarde o pacote. Os ficheiros ficam aqui apenas enquanto este ecrã está aberto. Não é conservação legal nem verificação de aceitação.','Adicionar documento','Adicionar comprovativo','Abrir pacote','Guardar pacote','Descarregar original','Integridade verificada. Autenticidade e resultado fiscal não verificados.','Ficheiro inválido, demasiado grande ou de outra fatura.','Escolha primeiro o documento do comprovativo.','Documento do comprovativo','Nenhum ficheiro adicionado.','A processar…']};
export const documentArchiveCopy=lang=>Object.fromEntries(['title','intro','add','receipt','open','save','download','verified','error','choose','target','empty','busy'].map((key,i)=>[key,(rows[lang]||rows.en)[i]]));
const persistence={it:'Gli originali vengono salvati su questo dispositivo. Esporta anche una copia: cancellare i dati del sito li elimina. Non è conservazione fiscale né verifica di accettazione. In caso di errore, non considerare il file salvato.',en:'Originals are saved on this device. Export a copy too: clearing site data removes them. This is not legal preservation or acceptance verification. If an error appears, do not consider the file saved.',de:'Originale werden auf diesem Gerät gespeichert. Exportiere eine Kopie: Das Löschen der Websitedaten entfernt sie. Keine rechtskonforme Archivierung oder Annahmeprüfung. Bei Fehlern gilt die Datei nicht als gespeichert.',fr:'Les originaux sont enregistrés sur cet appareil. Exportez aussi une copie : effacer les données du site les supprime. Ni archivage légal ni vérification d’acceptation. En cas d’erreur, le fichier ne doit pas être considéré comme enregistré.',es:'Los originales se guardan en este dispositivo. Exporta una copia: borrar los datos del sitio los elimina. No es conservación legal ni verificación de aceptación. Si aparece un error, no consideres guardado el archivo.',nl:'Originelen worden op dit apparaat opgeslagen. Exporteer ook een kopie: wissen van sitegegevens verwijdert ze. Geen wettelijke bewaring of controle van aanvaarding. Beschouw het bestand bij een fout niet als opgeslagen.',pt:'Os originais são guardados neste dispositivo. Exporte também uma cópia: apagar os dados do site elimina-os. Não é conservação legal nem verificação de aceitação. Em caso de erro, não considere o ficheiro guardado.'};
export const documentPersistenceCopy=lang=>persistence[lang]||persistence.en;
