const langs = ['it', 'en', 'de', 'fr', 'es', 'nl', 'pt'];
const copy = {
  forecastInside: ['La previsione era nell’intervallo', 'The result was within the forecast range', 'Das Ergebnis lag im Prognosebereich', 'Le résultat était dans la fourchette prévue', 'El resultado estuvo dentro del intervalo previsto', 'Het resultaat lag binnen de voorspelde band', 'O resultado ficou no intervalo previsto'],
  forecastOutside: ['Il risultato era fuori dall’intervallo', 'The result was outside the forecast range', 'Das Ergebnis lag außerhalb des Prognosebereichs', 'Le résultat était hors de la fourchette prévue', 'El resultado quedó fuera del intervalo previsto', 'Het resultaat lag buiten de voorspelde band', 'O resultado ficou fora do intervalo previsto'],
  forecastBody: ['Previsione del {0}, a {1} giorni: da {2} a {3}. Risultato registrato: {4}.', 'Forecast made on {0}, over {1} days: {2} to {3}. Recorded result: {4}.', 'Prognose vom {0} für {1} Tage: {2} bis {3}. Erfasstes Ergebnis: {4}.', 'Prévision du {0} sur {1} jours : de {2} à {3}. Résultat enregistré : {4}.', 'Previsión del {0} a {1} días: de {2} a {3}. Resultado registrado: {4}.', 'Voorspelling van {0} over {1} dagen: {2} tot {3}. Geregistreerd resultaat: {4}.', 'Previsão de {0} para {1} dias: de {2} a {3}. Resultado registado: {4}.'],
  checkpoint: ['Copia prima dell’aggiornamento', 'Copy from before the update', 'Kopie vor dem Update', 'Copie avant la mise à jour', 'Copia anterior a la actualización', 'Kopie van vóór de update', 'Cópia anterior à atualização'],
  checkpointMissing: ['Nessuna copia precedente disponibile. I backup attuali restano disponibili.', 'No earlier copy is available. Current backups remain available.', 'Keine frühere Kopie verfügbar. Aktuelle Backups bleiben verfügbar.', 'Aucune copie antérieure disponible. Les sauvegardes actuelles restent disponibles.', 'No hay una copia anterior disponible. Las copias actuales siguen disponibles.', 'Geen eerdere kopie beschikbaar. Huidige back-ups blijven beschikbaar.', 'Não existe uma cópia anterior disponível. As cópias atuais continuam disponíveis.'],
  checkpointWarning: ['Questa copia non è cifrata. Conservala in un posto sicuro.', 'This copy is not encrypted. Keep it somewhere safe.', 'Diese Kopie ist nicht verschlüsselt. Bewahre sie sicher auf.', 'Cette copie n’est pas chiffrée. Conserve-la en lieu sûr.', 'Esta copia no está cifrada. Guárdala en un lugar seguro.', 'Deze kopie is niet versleuteld. Bewaar deze veilig.', 'Esta cópia não está encriptada. Guarda-a num local seguro.'],
  patternMissing: ['Scegli un mercato: S&P 500, Nasdaq, Russell 2000, oro, argento, rame, petrolio, dollaro o bitcoin.', 'Choose a market: S&P 500, Nasdaq, Russell 2000, gold, silver, copper, oil, dollar or bitcoin.', 'Wähle einen Markt: S&P 500, Nasdaq, Russell 2000, Gold, Silber, Kupfer, Öl, Dollar oder Bitcoin.', 'Choisis un marché : S&P 500, Nasdaq, Russell 2000, or, argent, cuivre, pétrole, dollar ou bitcoin.', 'Elige un mercado: S&P 500, Nasdaq, Russell 2000, oro, plata, cobre, petróleo, dólar o bitcoin.', 'Kies een markt: S&P 500, Nasdaq, Russell 2000, goud, zilver, koper, olie, dollar of bitcoin.', 'Escolhe um mercado: S&P 500, Nasdaq, Russell 2000, ouro, prata, cobre, petróleo, dólar ou bitcoin.'],
  patternLow: ['{0}: {1} casi storici, troppo pochi per una stima (ne servono almeno {2}).', '{0}: {1} historical cases, too few for an estimate (at least {2} needed).', '{0}: {1} historische Fälle, zu wenige für eine Schätzung (mindestens {2} nötig).', '{0} : {1} cas historiques, trop peu pour une estimation (au moins {2} nécessaires).', '{0}: {1} casos históricos, insuficientes para una estimación (se necesitan al menos {2}).', '{0}: {1} historische gevallen, te weinig voor een schatting (minimaal {2} nodig).', '{0}: {1} casos históricos, insuficientes para uma estimativa (são necessários pelo menos {2}).'],
  patternResult: ['{0}: {1} casi storici tra {2} e {3}. Dopo un movimento di {4} in {5} giorni di borsa, nei {6} giorni successivi: mediana {7}, risultato positivo nel {8} dei casi. Decimo peggiore {9}, migliore {10}. È una frequenza storica, non una previsione.', '{0}: {1} historical cases from {2} to {3}. After a move of {4} over {5} trading days, the next {6} days: median {7}, positive in {8} of cases. Bottom decile {9}, top decile {10}. Historical frequency, not a forecast.', '{0}: {1} historische Fälle von {2} bis {3}. Nach einer Bewegung von {4} in {5} Handelstagen, in den nächsten {6} Tagen: Median {7}, positiv in {8} der Fälle. Unteres Dezil {9}, oberes Dezil {10}. Historische Häufigkeit, keine Prognose.', '{0} : {1} cas historiques de {2} à {3}. Après un mouvement de {4} sur {5} séances, les {6} séances suivantes : médiane {7}, résultat positif dans {8} des cas. Décile inférieur {9}, supérieur {10}. Fréquence historique, pas une prévision.', '{0}: {1} casos históricos de {2} a {3}. Tras un movimiento de {4} en {5} sesiones, en las siguientes {6}: mediana {7}, resultado positivo en el {8} de los casos. Decil inferior {9}, superior {10}. Frecuencia histórica, no una previsión.', '{0}: {1} historische gevallen van {2} tot {3}. Na een beweging van {4} in {5} handelsdagen, in de volgende {6} dagen: mediaan {7}, positief in {8} van de gevallen. Onderste deciel {9}, bovenste {10}. Historische frequentie, geen voorspelling.', '{0}: {1} casos históricos de {2} a {3}. Após um movimento de {4} em {5} sessões, nas {6} seguintes: mediana {7}, resultado positivo em {8} dos casos. Decil inferior {9}, superior {10}. Frequência histórica, não é uma previsão.'],
};
export function tIntegration(key, lang = 'en', ...values) {
  const index = langs.indexOf(lang);
  return (copy[key]?.[index < 0 ? 1 : index] || key).replace(/\{(\d+)\}/g, (_, i) => String(values[i] ?? ''));
}

export function formatPatternResult(result, lang = 'en') {
  if (!result?.trovato) return tIntegration('patternMissing', lang);
  const locale = langs.includes(lang) ? lang : 'en';
  const { chiave, nome, criterio: c, riassunto: r } = result;
  const names = { azioniUsa: 'S&P 500', tecnologia: 'Nasdaq', piccoleUsa: 'Russell 2000', oro: 'XAU', argento: 'XAG', rame: 'Copper / HG', petrolio: 'WTI', dollaro: 'USD', bitcoin: 'Bitcoin' };
  const asset = names[chiave] || nome;
  if (!r.abbastanza) return tIntegration('patternLow', locale, asset, r.casi, r.minCasi);
  const pct = n => new Intl.NumberFormat(locale, { style: 'percent', maximumFractionDigits: 1 }).format(n);
  const date = value => new Date(value + 'T00:00:00Z').toLocaleDateString(locale, { timeZone: 'UTC' });
  return tIntegration('patternResult', locale, asset, r.casi, date(r.primaData), date(r.ultimaData),
    pct(c.soglia * (c.direzione === 'caduta' ? -1 : 1)), c.finestraGiorni, c.orizzonteGiorni,
    pct(r.mediano), pct(r.quotaInGuadagno), pct(r.peggioreDecile), pct(r.miglioreDecile));
}
