const keys=['title','intro','note','add','resolve','open','done','stale','error','empty','export'];
const copy={
it:['Controlli e correzioni','Appunti locali da condividere con il commercialista. Non sono approvazioni fiscali né esiti SdI.','Cosa va controllato?','Aggiungi controllo','Ho verificato questa versione','Da controllare','Verificato da te','La fattura è cambiata: verifica di nuovo.','Controlla i dati. Nessuna modifica salvata.','Nessun controllo annotato. Questo non certifica la correttezza della fattura.','Esporta controlli'],
en:['Checks and corrections','Local notes to share with your accountant. These are not tax approvals or SdI outcomes.','What needs checking?','Add a check','I checked this version','To check','Checked by you','The invoice changed: check again.','Check the details. Nothing saved.','No checks recorded. This does not certify the invoice is correct.','Export checks'],
de:['Prüfungen und Korrekturen','Lokale Notizen für deine Steuerberatung. Keine steuerlichen Freigaben oder SdI-Ergebnisse.','Was ist zu prüfen?','Prüfung hinzufügen','Diese Version geprüft','Zu prüfen','Von dir geprüft','Die Rechnung wurde geändert: erneut prüfen.','Daten prüfen. Nichts gespeichert.','Keine Prüfungen notiert. Das bestätigt nicht die Richtigkeit der Rechnung.','Prüfungen exportieren'],
fr:['Contrôles et corrections','Notes locales à partager avec votre comptable. Ni validations fiscales ni résultats SdI.','Que faut-il vérifier ?','Ajouter un contrôle','J’ai vérifié cette version','À vérifier','Vérifié par vous','La facture a changé : vérifiez à nouveau.','Vérifiez les données. Rien enregistré.','Aucun contrôle noté. Cela ne certifie pas la facture.','Exporter les contrôles'],
es:['Controles y correcciones','Notas locales para compartir con tu gestor. No son aprobaciones fiscales ni resultados SdI.','¿Qué hay que revisar?','Añadir control','He revisado esta versión','Por revisar','Revisado por ti','La factura cambió: revísala de nuevo.','Revisa los datos. No se guardó nada.','No hay controles anotados. Esto no certifica la factura.','Exportar controles'],
nl:['Controles en correcties','Lokale notities voor je accountant. Geen fiscale goedkeuringen of SdI-resultaten.','Wat moet worden gecontroleerd?','Controle toevoegen','Ik heb deze versie gecontroleerd','Te controleren','Door jou gecontroleerd','De factuur is gewijzigd: controleer opnieuw.','Controleer de gegevens. Niets opgeslagen.','Geen controles genoteerd. Dit bevestigt niet dat de factuur juist is.','Controles exporteren'],
pt:['Verificações e correções','Notas locais para partilhar com o contabilista. Não são aprovações fiscais nem resultados SdI.','O que precisa de revisão?','Adicionar verificação','Verifiquei esta versão','Por verificar','Verificado por si','A fatura mudou: verifique novamente.','Verifique os dados. Nada guardado.','Sem verificações anotadas. Isto não certifica a fatura.','Exportar verificações']
};
export const invoiceReviewCopy=lang=>Object.fromEntries(keys.map((k,i)=>[k,(Object.hasOwn(copy,lang)?copy[lang]:copy.en)[i]]));
