const rows={
 it:['Leggi esito AEAT','Contenuto del file: provenienza e associazione alla fattura non verificate. Nessuno stato fiscale è stato modificato.','Formato non supportato o file non valido. L’originale resta disponibile.','Accettato nel file','Accettato con errori nel file','Scartato nel file','Annullamento','Registrazione','Invio duplicato: controlla il registro precedente','Nessun esito di singola fattura nel file.','Mostra altri 20'],
 en:['Read AEAT outcome','File content: origin and invoice association are not verified. No tax status has changed.','Unsupported format or invalid file. The original remains available.','Accepted in file','Accepted with errors in file','Rejected in file','Cancellation','Registration','Duplicate submission: check the previous record','No individual invoice outcome in this file.','Show 20 more'],
 de:['AEAT-Ergebnis lesen','Dateiinhalt: Herkunft und Rechnungszuordnung ungeprüft. Kein Steuerstatus wurde geändert.','Nicht unterstütztes Format oder ungültige Datei. Das Original bleibt verfügbar.','Laut Datei angenommen','Laut Datei mit Fehlern angenommen','Laut Datei abgelehnt','Stornierung','Registrierung','Doppelte Übermittlung: vorherigen Eintrag prüfen','Kein einzelnes Rechnungsergebnis in der Datei.','20 weitere anzeigen'],
 fr:['Lire le résultat AEAT','Contenu du fichier : origine et association à la facture non vérifiées. Aucun statut fiscal modifié.','Format non pris en charge ou fichier invalide. L’original reste disponible.','Accepté selon le fichier','Accepté avec erreurs selon le fichier','Rejeté selon le fichier','Annulation','Enregistrement','Envoi en double : vérifiez le registre précédent','Aucun résultat individuel de facture dans ce fichier.','Afficher 20 de plus'],
 es:['Leer resultado AEAT','Contenido del archivo: origen y asociación a la factura sin verificar. No se ha cambiado ningún estado fiscal.','Formato no compatible o archivo inválido. El original sigue disponible.','Aceptado según el archivo','Aceptado con errores según el archivo','Rechazado según el archivo','Anulación','Alta','Envío duplicado: revisa el registro anterior','No hay resultados individuales de facturas en el archivo.','Mostrar 20 más'],
 nl:['AEAT-resultaat lezen','Bestandsinhoud: herkomst en factuurkoppeling niet gecontroleerd. Geen fiscale status gewijzigd.','Niet-ondersteund formaat of ongeldig bestand. Het origineel blijft beschikbaar.','Volgens bestand aanvaard','Volgens bestand met fouten aanvaard','Volgens bestand afgewezen','Annulering','Registratie','Dubbele verzending: controleer het vorige record','Geen resultaat voor een afzonderlijke factuur in dit bestand.','Nog 20 tonen'],
 pt:['Ler resultado AEAT','Conteúdo do ficheiro: origem e associação à fatura não verificadas. Nenhum estado fiscal foi alterado.','Formato não suportado ou ficheiro inválido. O original continua disponível.','Aceite segundo o ficheiro','Aceite com erros segundo o ficheiro','Rejeitado segundo o ficheiro','Anulação','Registo','Envio duplicado: verifique o registo anterior','Sem resultados individuais de faturas neste ficheiro.','Mostrar mais 20']
};
export const nationalReceiptCopy=lang=>Object.fromEntries(['read','notice','error','Correcto','AceptadoConErrores','Incorrecto','Anulacion','Alta','duplicate','empty','more'].map((k,i)=>[k,(rows[lang]||rows.en)[i]]));
const sdi={it:['Leggi ricevuta SdI','Consegnato secondo il file','Scartato secondo il file','Recapito non riuscito secondo il file'],en:['Read SdI receipt','Delivered according to file','Rejected according to file','Delivery failed according to file'],de:['SdI-Beleg lesen','Laut Datei zugestellt','Laut Datei abgelehnt','Zustellung laut Datei fehlgeschlagen'],fr:['Lire le reçu SdI','Livré selon le fichier','Rejeté selon le fichier','Livraison échouée selon le fichier'],es:['Leer recibo SdI','Entregado según el archivo','Rechazado según el archivo','Entrega fallida según el archivo'],nl:['SdI-bewijs lezen','Volgens bestand afgeleverd','Volgens bestand afgewezen','Aflevering volgens bestand mislukt'],pt:['Ler recibo SdI','Entregue segundo o ficheiro','Rejeitado segundo o ficheiro','Entrega falhada segundo o ficheiro']};
export const sdiReceiptCopy=lang=>({...nationalReceiptCopy(lang),SdI:'SdI',...Object.fromEntries(['read','RicevutaConsegna','RicevutaScarto','RicevutaImpossibilitaRecapito'].map((k,i)=>[k,(sdi[lang]||sdi.en)[i]]))});
