const copy = {
  it: ['Limiti giornalieri per categoria (€)', 'Motivo dell’eccezione (facoltativo)', 'Es. hotel della conferenza', 'Il motivo accompagna il resoconto: non equivale a un’autorizzazione.', 'Usa queste regole per le nuove trasferte su questo dispositivo', 'Le trasferte esistenti mantengono le proprie regole.', 'Totale giornaliero oltre il limite', 'Motivo dichiarato dal dipendente'],
  en: ['Daily category limits (€)', 'Exception reason (optional)', 'E.g. conference hotel', 'The reason accompanies the report; it is not an authorization.', 'Use these rules for new trips on this device', 'Existing trips keep their own rules.', 'Daily total above the limit', 'Reason provided by the employee'],
  de: ['Tageslimits pro Kategorie (€)', 'Begründung der Ausnahme (optional)', 'Z. B. Konferenzhotel', 'Die Begründung begleitet den Bericht; sie ist keine Genehmigung.', 'Diese Regeln für neue Reisen auf diesem Gerät verwenden', 'Bestehende Reisen behalten ihre Regeln.', 'Tagessumme über dem Limit', 'Begründung des Mitarbeiters'],
  fr: ['Plafonds quotidiens par catégorie (€)', 'Motif de l’exception (facultatif)', 'Ex. hôtel de la conférence', 'Le motif accompagne le rapport ; ce n’est pas une autorisation.', 'Utiliser ces règles pour les nouveaux déplacements sur cet appareil', 'Les déplacements existants gardent leurs règles.', 'Total quotidien au-dessus du plafond', 'Motif déclaré par le salarié'],
  es: ['Límites diarios por categoría (€)', 'Motivo de la excepción (opcional)', 'Ej. hotel de la conferencia', 'El motivo acompaña el informe; no es una autorización.', 'Usar estas reglas para nuevos viajes en este dispositivo', 'Los viajes existentes conservan sus reglas.', 'Total diario por encima del límite', 'Motivo declarado por el empleado'],
  nl: ['Daglimieten per categorie (€)', 'Reden voor uitzondering (optioneel)', 'Bijv. conferentiehotel', 'De reden hoort bij het rapport; dit is geen toestemming.', 'Deze regels voor nieuwe reizen op dit apparaat gebruiken', 'Bestaande reizen behouden hun regels.', 'Dagtotaal boven de limiet', 'Reden opgegeven door de medewerker'],
  pt: ['Limites diários por categoria (€)', 'Motivo da exceção (opcional)', 'Ex. hotel da conferência', 'O motivo acompanha o relatório; não é uma autorização.', 'Usar estas regras para novas viagens neste dispositivo', 'As viagens existentes mantêm as suas regras.', 'Total diário acima do limite', 'Motivo declarado pelo funcionário'],
};
export const policyDetailsCopy = (lang, key) => (copy[lang] || copy.en)[key];
