const copy = {
  it: ['Sì', 'No', 'Non so', 'Indietro', 'Continua', 'Domanda', 'Da chiarire prima di decidere', 'Queste risposte richiedono una verifica con il commercialista. Nessun regime è stato cambiato.', 'Rivedi le risposte', 'Altre azioni', 'Rispondi per continuare', 'Esporta per il commercialista', 'Scegli il formato adatto a chi riceverà i dati.', 'Riepilogo da leggere o stampare', 'Tabella per un foglio di calcolo', 'Dati strutturati per software'],
  en: ['Yes', 'No', 'Not sure', 'Back', 'Continue', 'Question', 'Check these before deciding', 'Review these answers with your accountant. No tax regime has been changed.', 'Review answers', 'More actions', 'Answer to continue', 'Export for your accountant', 'Choose a format for the person receiving the data.', 'Summary to read or print', 'Table for a spreadsheet', 'Structured data for software'],
  de: ['Ja', 'Nein', 'Unsicher', 'Zurück', 'Weiter', 'Frage', 'Vor der Entscheidung klären', 'Prüfe diese Antworten mit deiner Steuerberatung. Die Steuerregelung wurde nicht geändert.', 'Antworten prüfen', 'Weitere Aktionen', 'Zum Fortfahren antworten', 'Für die Steuerberatung exportieren', 'Wähle ein Format für den Empfänger.', 'Zusammenfassung zum Lesen oder Drucken', 'Tabelle für eine Tabellenkalkulation', 'Strukturierte Daten für Software'],
  fr: ['Oui', 'Non', 'Je ne sais pas', 'Retour', 'Continuer', 'Question', 'À clarifier avant de décider', 'Vérifie ces réponses avec ton comptable. Aucun régime fiscal n’a été modifié.', 'Revoir les réponses', 'Autres actions', 'Réponds pour continuer', 'Exporter pour le comptable', 'Choisis un format adapté au destinataire.', 'Résumé à lire ou imprimer', 'Tableau pour un tableur', 'Données structurées pour un logiciel'],
  es: ['Sí', 'No', 'No lo sé', 'Atrás', 'Continuar', 'Pregunta', 'Acláralo antes de decidir', 'Revisa estas respuestas con tu asesor. No se ha cambiado ningún régimen fiscal.', 'Revisar respuestas', 'Más acciones', 'Responde para continuar', 'Exportar para tu asesor', 'Elige un formato para quien recibirá los datos.', 'Resumen para leer o imprimir', 'Tabla para una hoja de cálculo', 'Datos estructurados para software'],
  nl: ['Ja', 'Nee', 'Weet ik niet', 'Terug', 'Doorgaan', 'Vraag', 'Controleer dit voordat je beslist', 'Bespreek deze antwoorden met je accountant. Er is geen belastingregeling gewijzigd.', 'Antwoorden bekijken', 'Meer acties', 'Antwoord om door te gaan', 'Exporteren voor je accountant', 'Kies een formaat voor de ontvanger.', 'Overzicht om te lezen of af te drukken', 'Tabel voor een spreadsheet', 'Gestructureerde gegevens voor software'],
  pt: ['Sim', 'Não', 'Não sei', 'Voltar', 'Continuar', 'Pergunta', 'Esclareça antes de decidir', 'Confira estas respostas com seu contador. Nenhum regime fiscal foi alterado.', 'Rever respostas', 'Mais ações', 'Responda para continuar', 'Exportar para o contador', 'Escolha um formato para quem receberá os dados.', 'Resumo para ler ou imprimir', 'Tabela para uma planilha', 'Dados estruturados para software'],
};
const keys = ['yes','no','unknown','back','next','question','uncertainTitle','uncertainHint','review','more','answerFirst','exportTitle','exportHint','print','csv','json'];
export const taxJourneyCopy = lang => Object.fromEntries(keys.map((key,i) => [key,(copy[lang] || copy.en)[i]]));
