// Guided handoff, not a connector: no credentials, submissions or fiscal state.
const labels = {
  it: ['Passaggi sui portali ufficiali','Prepara','Apri il portale','Controlla','Torna a Momentum','Indietro','Continua','Apri il servizio ufficiale','Guida ufficiale','Si apre una nuova scheda. Nessun dato viene inviato da Momentum.','Questi sono passi della guida, non conferme di invio.'],
  en: ['Steps on official portals','Prepare','Open the portal','Check','Return to Momentum','Back','Continue','Open the official service','Official guide','Opens a new tab. Momentum sends no data.','These are guide steps, not submission confirmations.'],
  de: ['Schritte auf offiziellen Portalen','Vorbereiten','Portal öffnen','Prüfen','Zurück zu Momentum','Zurück','Weiter','Offiziellen Dienst öffnen','Offizielle Anleitung','Öffnet einen neuen Tab. Momentum übermittelt keine Daten.','Dies sind Anleitungsschritte, keine Versandbestätigungen.'],
  fr: ['Étapes sur les portails officiels','Préparer','Ouvrir le portail','Vérifier','Revenir à Momentum','Retour','Continuer','Ouvrir le service officiel','Guide officiel','Un nouvel onglet s’ouvre. Momentum ne transmet aucune donnée.','Ces étapes ne confirment aucun envoi.'],
  es: ['Pasos en los portales oficiales','Prepara','Abre el portal','Comprueba','Vuelve a Momentum','Atrás','Continuar','Abrir el servicio oficial','Guía oficial','Se abre otra pestaña. Momentum no envía datos.','Son pasos de la guía, no confirmaciones de envío.'],
  nl: ['Stappen op officiële portalen','Voorbereiden','Portaal openen','Controleren','Terug naar Momentum','Terug','Doorgaan','Officiële dienst openen','Officiële handleiding','Opent een nieuw tabblad. Momentum verstuurt geen gegevens.','Dit zijn stappen in de handleiding, geen indieningsbevestigingen.'],
  pt: ['Passos nos portais oficiais','Prepare','Abra o portal','Confira','Volte ao Momentum','Voltar','Continuar','Abrir o serviço oficial','Guia oficial','Abre uma nova aba. O Momentum não envia dados.','São passos do guia, não confirmações de envio.'],
};
const instructions = {
  it: {
    it: ['Prepara la fattura e scarica l’XML dal riepilogo. Il PDF è una copia di cortesia, non il file da trasmettere allo SdI.', 'Accedi a Fatture e Corrispettivi con l’identità richiesta dal portale. Cerca il servizio di trasmissione delle fatture e carica l’XML. Verifica prima di inviare.', 'Controlla la ricevuta nel portale: uno scarto richiede una correzione, non significa fattura emessa. Verifica anche l’adesione al servizio di conservazione: il backup Momentum non lo sostituisce.', 'Conserva XML e ricevuta. Torna a questa scheda; la guida non aggiorna lo stato della fattura. Se aggiorni il promemoria di trasmissione, ricorda che è una tua conferma, non una verifica SdI.'],
    ch: ['Per il rendiconto IVA, prepara documenti e importi del periodo. La QR-fattura serve al pagamento: non è una dichiarazione IVA.', 'Apri il portale AFC. Accedi con il metodo richiesto e verifica di essere autorizzato per l’impresa e il servizio Rendiconto IVA pro.', 'Seleziona impresa e periodo, controlla i dati e completa il rendiconto nel portale. L’export Momentum non è un file di dichiarazione eCH-0217.', 'Salva la conferma del portale e torna a Momentum. L’inoltro del rendiconto e il pagamento sono passaggi distinti: segui le istruzioni dell’AFC.'],
    es: ['Prepara dati del cliente, voci e imposte. Prima di usare l’app gratuita AEAT, verifica nella guida che copra il tuo caso. Momentum non trasmette registri VERI*FACTU.', 'Apri l’app di fatturazione AEAT e identificati con il metodo richiesto. Se l’accesso non riesce, usa la guida ufficiale qui sotto.', 'Compila e controlla la fattura nell’app AEAT prima di confermare. Non caricare l’XML italiano: non è un formato di invio spagnolo.', 'Scarica documento e conferma disponibili. Torna a Momentum evitando di registrare due volte lo stesso incasso. Fatturare non presenta automaticamente le dichiarazioni fiscali.'],
  },
  en: {
    it: ['Prepare the invoice and download its XML from the summary. The PDF is a courtesy copy, not the SdI transmission file.', 'Sign in to Fatture e Corrispettivi using the identity method it requests. Find invoice transmission and upload the XML. Review before sending.', 'Check the portal receipt: rejection requires correction and does not mean an invoice was issued. Also check enrolment in compliant preservation; a Momentum backup does not replace it.', 'Keep the XML and receipt, then return to this tab. This guide does not update invoice status. Updating the transmission reminder is your declaration, not an SdI verification.'],
    ch: ['For a VAT return, prepare the period’s documents and amounts. A QR bill is for payment, not a VAT return.', 'Open the ESTV portal, sign in as requested and check your business permissions for VAT return pro.', 'Select the business and period, review the figures and complete the return in the portal. Momentum exports are not eCH-0217 return files.', 'Save the portal confirmation and return to Momentum. Filing and payment are separate steps: follow the ESTV instructions.'],
    es: ['Prepare the customer details, items and taxes. Check the official guide to see whether the free AEAT app covers your case. Momentum does not transmit VERI*FACTU records.', 'Open the AEAT invoicing app and sign in as requested. If access fails, use the official guide below.', 'Complete and check the invoice in the AEAT app before confirming. Do not upload an Italian XML: it is not a Spanish submission format.', 'Download the available document and confirmation. Return to Momentum without recording the same receipt twice. Invoicing does not automatically file tax returns.'],
  },
  de: {
    it: ['Rechnung vorbereiten und XML in der Übersicht herunterladen. Das PDF ist eine Kopie, keine SdI-Übermittlungsdatei.', 'Bei Fatture e Corrispettivi wie angefordert anmelden. Rechnungsübermittlung suchen, XML hochladen und vor dem Versand prüfen.', 'Beleg im Portal prüfen: Eine Ablehnung erfordert eine Korrektur. Auch die Anmeldung zur gesetzeskonformen Aufbewahrung prüfen; ein Momentum-Backup ersetzt sie nicht.', 'XML und Beleg behalten und zu diesem Tab zurückkehren. Die Anleitung ändert keinen Rechnungsstatus. Eine manuelle Versandbestätigung ist keine SdI-Prüfung.'],
    ch: ['Für die MWST-Abrechnung Belege und Beträge der Periode vorbereiten. Die QR-Rechnung dient der Zahlung, nicht der MWST-Abrechnung.', 'ESTV-Portal öffnen, wie angefordert anmelden und Berechtigung für das Unternehmen und MWST-Abrechnung pro prüfen.', 'Unternehmen und Periode auswählen, Zahlen prüfen und im Portal abrechnen. Momentum-Exporte sind keine eCH-0217-Abrechnungsdateien.', 'Portalbestätigung speichern und zu Momentum zurückkehren. Einreichung und Zahlung sind getrennte Schritte: Hinweise der ESTV beachten.'],
    es: ['Kundendaten, Positionen und Steuern vorbereiten. In der offiziellen Anleitung prüfen, ob die kostenlose AEAT-App deinen Fall abdeckt. Momentum übermittelt keine VERI*FACTU-Datensätze.', 'AEAT-Rechnungsapp öffnen und wie angefordert anmelden. Bei Zugangsproblemen die offizielle Anleitung unten nutzen.', 'Rechnung in der AEAT-App ausfüllen und vor der Bestätigung prüfen. Kein italienisches XML hochladen: Es ist kein spanisches Übermittlungsformat.', 'Verfügbare Rechnung und Bestätigung herunterladen. Zu Momentum zurückkehren, ohne denselben Zahlungseingang doppelt zu erfassen. Rechnungen reichen keine Steuererklärungen automatisch ein.'],
  },
  fr: {
    it: ['Prépare la facture et télécharge son XML depuis le récapitulatif. Le PDF est une copie, pas le fichier à transmettre au SdI.', 'Connecte-toi à Fatture e Corrispettivi avec le moyen demandé. Cherche la transmission de factures et charge le XML. Vérifie avant d’envoyer.', 'Vérifie le reçu du portail : un rejet exige une correction. Vérifie aussi l’adhésion à la conservation conforme ; la sauvegarde Momentum ne la remplace pas.', 'Garde le XML et le reçu, puis reviens à cet onglet. Ce guide ne modifie aucun statut. Une confirmation manuelle d’envoi n’est pas une vérification SdI.'],
    ch: ['Pour le décompte TVA, prépare les justificatifs et montants de la période. La QR-facture sert au paiement, pas à déclarer la TVA.', 'Ouvre le portail AFC, connecte-toi comme demandé et vérifie tes droits pour l’entreprise et Décompte TVA pro.', 'Choisis l’entreprise et la période, vérifie les chiffres et complète le décompte sur le portail. Les exports Momentum ne sont pas des fichiers eCH-0217.', 'Enregistre la confirmation du portail et reviens à Momentum. Déclaration et paiement sont distincts : suis les instructions de l’AFC.'],
    es: ['Prépare client, prestations et taxes. Vérifie dans le guide si l’application gratuite AEAT couvre ton cas. Momentum ne transmet pas de registres VERI*FACTU.', 'Ouvre l’application de facturation AEAT et identifie-toi comme demandé. En cas de problème, utilise le guide officiel ci-dessous.', 'Complète et vérifie la facture dans l’application AEAT avant de confirmer. Ne charge pas un XML italien : ce n’est pas le format espagnol.', 'Télécharge le document et la confirmation disponibles. Reviens à Momentum sans saisir deux fois le même encaissement. Facturer ne dépose pas automatiquement les déclarations fiscales.'],
  },
  es: {
    it: ['Prepara la factura y descarga el XML del resumen. El PDF es una copia, no el archivo de envío al SdI.', 'Accede a Fatture e Corrispettivi con la identificación solicitada. Busca el envío de facturas y carga el XML. Revisa antes de enviar.', 'Consulta el recibo: un rechazo exige corregir, no significa factura emitida. Comprueba también la adhesión a la conservación legal; el backup de Momentum no la sustituye.', 'Guarda XML y recibo y vuelve a esta pestaña. La guía no cambia estados. Una confirmación manual de envío no es una verificación SdI.'],
    ch: ['Para la declaración de IVA, prepara documentos e importes del período. La factura QR sirve para pagar, no para declarar IVA.', 'Abre el portal AFC, identifícate como se solicita y comprueba los permisos de la empresa para el servicio IVA pro.', 'Selecciona empresa y período, revisa las cifras y completa la declaración en el portal. Los archivos de Momentum no son declaraciones eCH-0217.', 'Guarda la confirmación y vuelve a Momentum. Presentar y pagar son pasos diferentes: sigue las instrucciones de la AFC.'],
    es: ['Prepara cliente, conceptos e impuestos. Comprueba en la guía si la aplicación gratuita AEAT cubre tu caso. Momentum no envía registros VERI*FACTU.', 'Abre la aplicación de facturación AEAT e identifícate como se solicita. Si falla el acceso, usa la guía oficial de abajo.', 'Completa y revisa la factura en la aplicación AEAT antes de confirmar. No cargues un XML italiano: no es un formato de envío español.', 'Descarga el documento y la confirmación disponibles. Vuelve a Momentum sin duplicar el mismo cobro. Facturar no presenta automáticamente las declaraciones tributarias.'],
  },
  nl: {
    it: ['Maak de factuur klaar en download het XML uit het overzicht. De PDF is een kopie, niet het bestand voor SdI.', 'Meld je aan bij Fatture e Corrispettivi zoals gevraagd. Zoek factuurverzending, upload het XML en controleer vóór verzending.', 'Controleer het ontvangstbewijs: een afwijzing vereist correctie. Controleer ook deelname aan wettelijke bewaring; een Momentum-backup vervangt die niet.', 'Bewaar XML en ontvangstbewijs en keer terug naar dit tabblad. De handleiding wijzigt geen status. Een handmatige verzendbevestiging is geen SdI-controle.'],
    ch: ['Verzamel documenten en bedragen van het tijdvak voor de btw-aangifte. De QR-factuur is voor betaling, niet voor btw-aangifte.', 'Open het ESTV-portaal, meld je aan zoals gevraagd en controleer je rechten voor het bedrijf en btw-aangifte pro.', 'Selecteer bedrijf en tijdvak, controleer bedragen en vul de aangifte in het portaal in. Momentum-exports zijn geen eCH-0217-aangiftebestanden.', 'Bewaar de bevestiging en keer terug naar Momentum. Aangifte en betaling zijn aparte stappen: volg de ESTV-instructies.'],
    es: ['Bereid klantgegevens, posten en belastingen voor. Controleer in de officiële gids of de gratis AEAT-app bij je situatie past. Momentum verstuurt geen VERI*FACTU-registers.', 'Open de AEAT-facturatieapp en meld je aan zoals gevraagd. Gebruik bij toegangsproblemen de officiële gids hieronder.', 'Vul de factuur in de AEAT-app in en controleer vóór bevestiging. Upload geen Italiaans XML: dit is geen Spaans indieningsformaat.', 'Download het beschikbare document en de bevestiging. Keer terug zonder dezelfde ontvangst dubbel te boeken. Factureren dient niet automatisch belastingaangiften in.'],
  },
  pt: {
    it: ['Prepare a fatura e baixe o XML no resumo. O PDF é uma cópia, não o arquivo para enviar ao SdI.', 'Entre em Fatture e Corrispettivi com a identificação solicitada. Procure a transmissão de faturas, carregue o XML e confira antes de enviar.', 'Confira o recibo: uma rejeição exige correção. Verifique também a adesão à conservação legal; o backup do Momentum não a substitui.', 'Guarde XML e recibo e volte a esta aba. O guia não altera estados. Uma confirmação manual de envio não é uma verificação SdI.'],
    ch: ['Para declarar IVA, prepare documentos e valores do período. A fatura QR serve ao pagamento, não à declaração de IVA.', 'Abra o portal AFC, entre conforme solicitado e confira a autorização da empresa para o serviço IVA pro.', 'Selecione empresa e período, confira os valores e complete a declaração no portal. Os arquivos do Momentum não são declarações eCH-0217.', 'Salve a confirmação e volte ao Momentum. Declarar e pagar são passos diferentes: siga as instruções da AFC.'],
    es: ['Prepare cliente, itens e impostos. Confira no guia se o aplicativo gratuito AEAT atende seu caso. O Momentum não envia registros VERI*FACTU.', 'Abra o aplicativo de faturação AEAT e identifique-se conforme solicitado. Se o acesso falhar, use o guia oficial abaixo.', 'Preencha e confira a fatura no aplicativo AEAT antes de confirmar. Não carregue XML italiano: não é um formato espanhol de envio.', 'Baixe o documento e a confirmação disponíveis. Volte sem registrar duas vezes o mesmo recebimento. Faturar não entrega automaticamente declarações fiscais.'],
  },
};
// wizardUrl (feedback utente 2026-09-21, verificato raggiungibile con
// curl -I prima di scriverlo): il link diretto al servizio di trasmissione
// fatture (fatturewizard) atterra dritto sulla schermata giusta SOLO se sei
// già autenticato sul portale — usato apposta solo nel passo 2 (dopo il
// login del passo 1 in mountTaxHandoff, main.js), mai come primo link:
// prima dell'autenticazione rimanderebbe comunque al login, ma dare per
// primo un link che sembra specifico e invece rimbalza è la stessa
// confusione ("ti mette a cercare ogni cosa dentro quel sito") che il
// feedback segnala.
const portals = {
  it: { name: 'Fatture e Corrispettivi · SdI', url: 'https://ivaservizi.agenziaentrate.gov.it/portale/', wizardUrl: 'https://ivaservizi.agenziaentrate.gov.it/ser/fatturewizard/#/home', help: 'https://www.fiscooggi.it/guideagenzia/fattura-elettronica-e-servizi-gratuiti-dellagenzia-delle-entrate-settembre-2018' },
  ch: { name: 'AFC / ESTV · IVA', url: 'https://estvportal.estv.admin.ch/', help: 'https://www.estv.admin.ch/it/rendiconto-iva-online' },
  es: { name: 'AEAT · VERI*FACTU', url: 'https://www1.agenciatributaria.gob.es/wlpl/TIKE-CONT/MenuAplicacionFacturacion', help: 'https://sede.agenciatributaria.gob.es/Sede/iva/sistemas-informaticos-facturacion-verifactu.html' },
};
// Feedback utente 2026-09-21: dare SUBITO il link diretto al servizio di
// trasmissione (fatturewizard) è la stessa confusione del link generico —
// se non sei ancora autenticato ti rimbalza al login comunque. Questa
// seconda etichetta chiarisce ESPLICITAMENTE che va aperta DOPO il primo
// link (l'accesso), mai come alternativa. Solo per l'Italia: è l'unico
// Paese con un deep-link verificato al servizio esatto (curl -I, 21/09/2026).
const wizardLabels = {
  it: ['Poi, vai dritto alla trasmissione', 'Apri questo SOLO dopo aver effettuato l’accesso sopra: se non sei ancora autenticato, ti chiederà comunque di accedere prima.'],
  en: ['Then, go straight to transmission', 'Open this ONLY after signing in above: if you are not authenticated yet, it will still ask you to sign in first.'],
  de: ['Dann direkt zur Übermittlung', 'Öffne dies ERST nach der Anmeldung oben: bist du noch nicht angemeldet, wirst du trotzdem zuerst zur Anmeldung geführt.'],
  fr: ['Ensuite, va directement à la transmission', 'Ouvre ce lien SEULEMENT après t’être connecté ci-dessus : si tu n’es pas encore authentifié, il te demandera quand même de te connecter d’abord.'],
  es: ['Luego, ve directo a la transmisión', 'Abre esto SOLO después de haber accedido arriba: si aún no estás autenticado, igualmente te pedirá iniciar sesión primero.'],
  nl: ['Ga dan meteen naar de verzending', 'Open dit PAS nadat je hierboven bent ingelogd: ben je nog niet geverifieerd, dan word je alsnog eerst gevraagd in te loggen.'],
  pt: ['Depois, vá direto à transmissão', 'Abra isto SÓ depois de ter entrado acima: se ainda não estiveres autenticado, mesmo assim vai pedir para entrares primeiro.'],
};
export function taxHandoffGuide(country, lang = 'en') {
  const key = String(country || '').trim().toLowerCase();
  if (!Object.hasOwn(portals, key)) return null;
  const language = Object.hasOwn(labels, lang) ? lang : 'en';
  const l = labels[language];
  const wl = wizardLabels[language] || wizardLabels.en;
  return { ...portals[key], country: key, title: l[0], back: l[5], next: l[6], open: l[7], helpLabel: l[8], external: l[9], note: l[10],
    wizardOpen: wl[0], wizardNote: wl[1],
    steps: instructions[language][key].map((body, i) => ({ title: l[i + 1], body })) };
}
