import { tripIssueLabel } from '../../src/i18n/trip-checks.js';
const words={
it:['Resoconti aziendali','Da verificare','Tutti','Mostra altri','Approva','Chiedi modifiche','Motivo o nota','Nessun resoconto in questa vista.','Operazione non riuscita. Riapri il resoconto e riprova.','Torna alla lista','Esito registrato','Scarica allegato','Esiste una versione più recente.','Scrivi cosa deve essere corretto.','Caricamento…','Le regole sono cambiate: richiedi un aggiornamento.','Approvato','Modifiche richieste','In attesa','Eccezione dichiarata'],
en:['Company reports','To review','All','Show more','Approve','Request changes','Reason or note','No reports in this view.','Unable to complete. Reopen the report and retry.','Back to list','Decision recorded','Download attachment','A newer version exists.','Write what needs correcting.','Loading…','Rules changed: request an update.','Approved','Changes requested','Pending','Declared exception'],
de:['Unternehmensberichte','Zu prüfen','Alle','Mehr anzeigen','Genehmigen','Änderungen anfordern','Begründung oder Notiz','Keine Berichte in dieser Ansicht.','Vorgang fehlgeschlagen. Bericht erneut öffnen und versuchen.','Zurück zur Liste','Entscheidung gespeichert','Beleg herunterladen','Eine neuere Version existiert.','Beschreibe die nötige Korrektur.','Wird geladen…','Regeln geändert: Aktualisierung anfordern.','Genehmigt','Änderungen angefordert','Ausstehend','Erklärte Ausnahme'],
fr:['Rapports de l’entreprise','À vérifier','Tous','Afficher plus','Approuver','Demander des modifications','Motif ou note','Aucun rapport dans cette vue.','Échec. Rouvrez le rapport et réessayez.','Retour à la liste','Décision enregistrée','Télécharger la pièce jointe','Une version plus récente existe.','Indiquez ce qui doit être corrigé.','Chargement…','Règles modifiées : demandez une mise à jour.','Approuvé','Modifications demandées','En attente','Exception déclarée'],
es:['Informes de empresa','Por revisar','Todos','Mostrar más','Aprobar','Pedir cambios','Motivo o nota','No hay informes en esta vista.','No se pudo completar. Abre de nuevo el informe e inténtalo.','Volver a la lista','Decisión registrada','Descargar adjunto','Existe una versión más reciente.','Indica qué hay que corregir.','Cargando…','Reglas cambiadas: solicita una actualización.','Aprobado','Cambios solicitados','Pendiente','Excepción declarada'],
nl:['Bedrijfsrapporten','Te controleren','Alle','Meer tonen','Goedkeuren','Wijzigingen vragen','Reden of notitie','Geen rapporten in deze weergave.','Niet gelukt. Open het rapport opnieuw en probeer nogmaals.','Terug naar lijst','Besluit opgeslagen','Bijlage downloaden','Er bestaat een nieuwere versie.','Schrijf wat moet worden aangepast.','Laden…','Regels gewijzigd: vraag een update.','Goedgekeurd','Wijzigingen gevraagd','In afwachting','Opgegeven uitzondering'],
pt:['Relatórios da empresa','A verificar','Todos','Mostrar mais','Aprovar','Pedir alterações','Motivo ou nota','Nenhum relatório nesta vista.','Não foi possível concluir. Reabra o relatório e tente novamente.','Voltar à lista','Decisão registada','Descarregar anexo','Existe uma versão mais recente.','Indique o que deve ser corrigido.','A carregar…','Regras alteradas: peça uma atualização.','Aprovado','Alterações pedidas','Pendente','Exceção declarada'],
};
const progressive={it:['Verifica tutti i documenti','Riepilogo: documenti non ancora verificati.'],en:['Check all documents','Summary: documents not checked yet.'],de:['Alle Belege pr�fen','�bersicht: Belege noch nicht gepr�ft.'],fr:['V�rifier tous les documents','R�sum� : documents pas encore v�rifi�s.'],es:['Verificar todos los documentos','Resumen: documentos a�n sin verificar.'],nl:['Alle documenten controleren','Overzicht: documenten nog niet gecontroleerd.'],pt:['Verificar todos os documentos','Resumo: documentos ainda n�o verificados.']};
export function inboxPage(){
 const nonce=crypto.randomUUID();const labels=Object.fromEntries(Object.keys(words).map(lang=>[lang,Object.fromEntries(['missing_attachment','policy_limit','policy_daily','policy_currency','invalid_policy','invalid_attachment','revision_conflict','invalid_amount','invalid_date'].map(code=>[code,tripIssueLabel(lang,code)]))]));
 return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Momentum</title><style nonce="${nonce}">
 :root{font-family:system-ui,sans-serif;color-scheme:dark;background:#0c0c15;color:#f4f2ff}*{box-sizing:border-box}body{margin:0;padding:clamp(16px,4vw,36px)}main{max-width:760px;margin:auto}button,textarea,a{font:inherit;min-height:48px;border-radius:14px}button,a{padding:12px 16px;color:inherit;border:1px solid #4b425d;background:#211a32;text-decoration:none;cursor:pointer}button{transition:transform .15s}button:active{transform:scale(.98)}button:disabled{opacity:.5;cursor:default}button:focus-visible,textarea:focus-visible,a:focus-visible{outline:3px solid #c6b2ff;outline-offset:3px}nav{display:flex;gap:12px;margin:20px 0;flex-wrap:wrap}nav button[aria-pressed=true],#approve{background:#b4a1ff;color:#171121}article,#detail{padding:20px;border:1px solid #3c344a;border-radius:22px;margin:14px 0;background:linear-gradient(130deg,#231d32,#14131e)}#list button{display:block;width:100%;text-align:left;margin:10px 0;overflow-wrap:anywhere}p{line-height:1.6;overflow-wrap:anywhere}textarea{width:100%;padding:12px;background:#111019;color:inherit;border:1px solid #645873}label{display:block;margin:16px 0 8px}#actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px}#actions button{flex:1}#status{min-height:28px}.warning{border-left:3px solid #e8bb72;padding-left:12px}a{display:inline-block}[hidden]{display:none!important}@media(prefers-reduced-motion:reduce){button{transition:none}}
 </style><main><p>MOMENTUM</p><h1 id="title"></h1><p id="status" role="status" aria-live="polite"></p><nav id="filters"><button id="pending" aria-pressed="true"></button><button id="all" aria-pressed="false"></button></nav><div id="list"></div><button id="more" hidden></button><section id="detail" hidden><button id="back"></button><h2 id="name"></h2><p id="state"></p><p id="exception"></p><p id="verification" role="status"></p><button id="verify" hidden></button><div id="expenses"></div><div id="decision" hidden><label id="note-label" for="note"></label><textarea id="note" maxlength="1000" rows="3"></textarea><div id="actions"><button id="approve"></button><button id="changes"></button></div></div></section></main>
 <script nonce="${nonce}">
 const progressive=${JSON.stringify(progressive)};const dictionary=${JSON.stringify(words)},issueLabels=${JSON.stringify(labels)};const params=new URLSearchParams(location.search),lang=(params.get('lang')||navigator.language||'en').split('-')[0],t=dictionary[lang]||dictionary.en;document.documentElement.lang=dictionary[lang]?lang:'en';const company=params.get('company'),el=id=>document.getElementById(id),base='/v1/companies/'+encodeURIComponent(company)+'/reports';
 for(const[id,n]of Object.entries({title:0,pending:1,all:2,more:3,approve:4,changes:5,'note-label':6,back:9}))el(id).textContent=t[n];let cursor=null,filter='pending',current=null,busy=false,generation=0;
 const stateName=value=>t[value==='approved'?16:value==='changes_requested'?17:18];
 async function api(path,body,hash){const response=await fetch(path,{credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(20000),...(body?{method:'POST',headers:{'Content-Type':'application/json','If-Match':'"'+hash+'"'},body:JSON.stringify(body)}:{})});if(!response.ok)throw new Error();return response.json()}
 async function list(reset=true){const turn=++generation;el('status').textContent=t[14];el('detail').hidden=true;el('list').hidden=false;el('filters').hidden=false;el('more').disabled=true;if(reset){cursor=null;el('list').replaceChildren()}try{const result=await api(base+'?filter='+filter+(cursor?'&after='+cursor:''));if(turn!==generation)return;for(const report of result.reports){const button=document.createElement('button');button.textContent=(report.name||report.trip_id)+' · v'+report.revision+' · '+stateName(report.decision);button.onclick=()=>open(report.id);el('list').append(button)}cursor=result.nextCursor;el('more').hidden=!cursor;el('status').textContent=el('list').children.length?'':t[7]}catch{if(turn===generation)el('status').textContent=t[8]}finally{if(turn===generation)el('more').disabled=false}}
 async function open(id,full=false){const savedNote=full?el('note').value:'';const turn=++generation;current=null;el('detail').hidden=false;el('decision').hidden=true;el('verify').hidden=true;el('verification').textContent='';el('list').hidden=true;el('filters').hidden=true;el('more').hidden=true;el('expenses').replaceChildren();el('name').textContent='';el('state').textContent='';el('exception').textContent='';el('status').textContent=t[14];try{const report=await api(base+'/'+id+(full?'':'?view=summary'));if(turn!==generation)return;current=report;el('verify').hidden=full;el('verify').textContent=(progressive[lang]||progressive.en)[0];el('verification').textContent=full?'':(progressive[lang]||progressive.en)[1];el('name').textContent=report.archive.trip.name||report.trip_id;el('state').textContent=stateName(report.decision)+(report.note?' · '+report.note:'');el('status').textContent=report.superseded?t[12]:report.policyStale?t[15]:'';const reason=report.archive.trip.receiptPolicy?.exceptionReason;el('exception').textContent=reason?t[19]+': '+reason:'';
 report.archive.transactions.forEach((tx,index)=>{const card=document.createElement('article'),heading=document.createElement('strong');heading.textContent=tx.description||tx.tripCategory||tx.id;card.append(heading);const amount=document.createElement('p');amount.textContent=tx.date+' · '+new Intl.NumberFormat(document.documentElement.lang,{style:'currency',currency:tx.currency||'EUR'}).format(tx.amount);card.append(amount);for(const issue of (report.checks?.issues||[]).filter(i=>i.index===index&&i.severity!=='info')){const p=document.createElement('p');p.className='warning';p.textContent=(issueLabels[lang]||issueLabels.en)[issue.code]||t[1];card.append(p)}if(tx.hasAttachment&&!tx.receiptImage){const button=document.createElement('button');button.textContent=t[11];button.onclick=async()=>{button.disabled=true;button.textContent=t[14];try{const file=await api(base+'/'+id+'?attachment='+index);if(turn!==generation)return;if(file.fingerprint!==report.fingerprint)throw Error();const a=document.createElement('a');a.textContent=t[11];a.href=file.receiptImage;a.download='receipt-'+index;button.replaceWith(a);a.click()}catch{if(turn===generation){button.disabled=false;button.textContent=t[11];el('status').textContent=t[8]}}};card.append(button)}if(tx.receiptImage){const a=document.createElement('a');a.textContent=t[11];a.href=tx.receiptImage;a.download='receipt-'+index+(tx.receiptImage.startsWith('data:application/pdf')?'.pdf':'.image');card.append(a)}el('expenses').append(card)});for(const item of report.archive.trip.offeredItems||[]){const card=document.createElement('article');card.textContent=(item.description||item.category||'')+' \u00b7 '+new Intl.NumberFormat(document.documentElement.lang,{style:'currency',currency:'EUR'}).format(item.amount);const label=document.createElement('p');label.textContent=({it:'Pagato dall\u2019azienda',en:'Paid by the company',de:'Vom Unternehmen bezahlt',fr:'Pay\u00e9 par l\u2019entreprise',es:'Pagado por la empresa',nl:'Betaald door het bedrijf',pt:'Pago pela empresa'})[lang]||'Paid by the company';card.prepend(label);el('expenses').append(card)}el('note').value=savedNote;el('decision').hidden=!report.canDecide;el('approve').disabled=report.policyStale||!report.attachmentContentsVerified;el('changes').disabled=false;
 }catch{if(turn===generation)el('status').textContent=t[8]}}
 async function decide(decision){if(busy||!current||(decision==='approved'&&!current.attachmentContentsVerified))return;if(decision==='changes_requested'&&!el('note').value.trim()){el('status').textContent=t[13];el('note').focus();return}busy=true;el('approve').disabled=true;el('changes').disabled=true;const report=current;try{await api(base+'/'+report.id+'/decision',{decision,note:el('note').value.trim()},report.fingerprint);if(current===report){el('decision').hidden=true;el('state').textContent=stateName(decision);el('status').textContent=t[10]}}catch{if(current===report){el('status').textContent=t[8];el('approve').disabled=report.policyStale||!report.attachmentContentsVerified;el('changes').disabled=false}}finally{busy=false}}
 el('pending').onclick=()=>{filter='pending';el('pending').setAttribute('aria-pressed','true');el('all').setAttribute('aria-pressed','false');list()};el('all').onclick=()=>{filter='all';el('pending').setAttribute('aria-pressed','false');el('all').setAttribute('aria-pressed','true');list()};el('more').onclick=()=>list(false);el('back').onclick=()=>{current=null;list()};el('verify').onclick=()=>{if(current)open(current.id,true)};el('approve').onclick=()=>decide('approved');el('changes').onclick=()=>decide('changes_requested');if(/^[a-zA-Z0-9_-]{1,80}$/.test(company||''))list();else el('status').textContent=t[8];
 </script></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'`}});
}
