const copy = {
  it: ['Il tuo spazio di lavoro', 'Verifico il tuo invito…', 'Entra nel team', 'Apri Momentum', 'Accesso attivato. Le spese personali non sono state condivise.', 'Invito non disponibile per questo account. Chiedi un nuovo invito al responsabile.', 'Non riesco a collegarmi. Riprova.', 'Dipendente', 'Responsabile', 'Revisore', 'Amministratore delle policy', 'Entrando attivi l’accesso allo spazio aziendale.'],
  en: ['Your workspace', 'Checking your invitation…', 'Join the team', 'Open Momentum', 'Access enabled. Your personal expenses have not been shared.', 'Invitation unavailable for this account. Ask your administrator for a new invitation.', 'Unable to connect. Try again.', 'Employee', 'Reviewer', 'Auditor', 'Policy administrator', 'Joining enables access to the company workspace.'],
  de: ['Dein Arbeitsbereich', 'Einladung wird geprüft…', 'Team beitreten', 'Momentum öffnen', 'Zugriff aktiviert. Persönliche Ausgaben wurden nicht geteilt.', 'Einladung für dieses Konto nicht verfügbar. Bitte um eine neue Einladung.', 'Verbindung fehlgeschlagen. Versuche es erneut.', 'Mitarbeiter', 'Verantwortlicher', 'Prüfer', 'Richtlinienadministrator', 'Der Beitritt aktiviert den Zugriff auf den Unternehmensbereich.'],
  fr: ['Votre espace de travail', 'Vérification de votre invitation…', 'Rejoindre l’équipe', 'Ouvrir Momentum', 'Accès activé. Vos dépenses personnelles n’ont pas été partagées.', 'Invitation indisponible pour ce compte. Demandez une nouvelle invitation.', 'Connexion impossible. Réessayez.', 'Salarié', 'Responsable', 'Auditeur', 'Administrateur des règles', 'Rejoindre active l’accès à l’espace de l’entreprise.'],
  es: ['Tu espacio de trabajo', 'Comprobando tu invitación…', 'Unirme al equipo', 'Abrir Momentum', 'Acceso activado. Tus gastos personales no se han compartido.', 'Invitación no disponible para esta cuenta. Solicita una nueva invitación.', 'No se puede conectar. Inténtalo de nuevo.', 'Empleado', 'Responsable', 'Auditor', 'Administrador de políticas', 'Al unirte activas el acceso al espacio de la empresa.'],
  nl: ['Je werkruimte', 'Je uitnodiging controleren…', 'Lid worden', 'Momentum openen', 'Toegang ingeschakeld. Je persoonlijke uitgaven zijn niet gedeeld.', 'Uitnodiging niet beschikbaar voor dit account. Vraag een nieuwe uitnodiging.', 'Geen verbinding. Probeer opnieuw.', 'Medewerker', 'Beoordelaar', 'Auditor', 'Beleidsbeheerder', 'Deelnemen geeft toegang tot de bedrijfsruimte.'],
  pt: ['O seu espaço de trabalho', 'A verificar o convite…', 'Entrar na equipa', 'Abrir Momentum', 'Acesso ativado. As suas despesas pessoais não foram partilhadas.', 'Convite indisponível para esta conta. Peça um novo convite.', 'Não foi possível ligar. Tente novamente.', 'Funcionário', 'Responsável', 'Auditor', 'Administrador de políticas', 'Entrar ativa o acesso ao espaço da empresa.'],
};
export function joinPage() {
  const nonce = crypto.randomUUID();
  return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Momentum</title>
  <style nonce="${nonce}">
  :root{color-scheme:dark;font-family:system-ui,sans-serif;background:#0b0b13;color:#f5f4ff}*{box-sizing:border-box}body{margin:0;min-height:100svh;display:grid;place-items:center;padding:24px}main{width:min(100%,460px);padding:clamp(24px,6vw,40px);border:1px solid #39364c;border-radius:28px;background:radial-gradient(at 0 0,#27213f,#13131e 70%);box-shadow:0 20px 80px #0006}h1{font-size:clamp(24px,6vw,32px);line-height:1.2}p{color:#c5c2d4;line-height:1.6;overflow-wrap:anywhere}button,a{display:block;width:100%;min-height:48px;padding:14px 18px;border-radius:16px;font:inherit;font-weight:650;text-align:center}button{border:0;background:#afa0ff;color:#141021;cursor:pointer;transition:transform .15s}button:active{transform:scale(.98)}button:disabled{opacity:.55;cursor:wait}a{color:#ddd5ff;margin-top:10px}button:focus-visible,a:focus-visible{outline:3px solid white;outline-offset:4px}.brand{letter-spacing:.12em;font-size:13px}svg{height:48px;width:48px;stroke:#b7a8ff;fill:none;stroke-width:1.5}[hidden]{display:none!important}@media(prefers-reduced-motion:reduce){button{transition:none}}
  </style><main><svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="24" r="9"/><ellipse cx="24" cy="24" rx="22" ry="13" transform="rotate(-30 24 24)"/></svg><p class="brand">MOMENTUM</p><h1 id="title"></h1><p id="company"></p><p id="status" role="status" aria-live="polite"></p><button id="join" hidden></button><a id="open" href="/" hidden></a></main>
  <script nonce="${nonce}">
  const dictionary=${JSON.stringify(copy)};
  const language=(new URLSearchParams(location.search).get('lang')||navigator.language||'en').split('-')[0];
  const text=dictionary[language]||dictionary.en;document.documentElement.lang=dictionary[language]?language:'en';
  const title=document.getElementById('title'),status=document.getElementById('status'),company=document.getElementById('company'),join=document.getElementById('join'),open=document.getElementById('open');
  title.textContent=text[0];status.textContent=text[1];join.textContent=text[2];open.textContent=text[3];
  const token=location.hash.slice(1);
  async function call(action){const response=await fetch('/v1/invitations/'+action,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});if(!response.ok)throw new Error(response.status>=500?'network':'unavailable');return response.json()}
  async function preview(){try{const result=await call('preview');company.textContent=result.companyName+' · '+text[({employee:7,reviewer:8,auditor:9,policy_admin:10})[result.role]];status.textContent=text[11];join.hidden=false}catch(error){status.textContent=text[5];open.hidden=false}}
  join.onclick=async()=>{join.disabled=true;try{await call('accept');history.replaceState(null,'',location.pathname);status.textContent=text[4];join.hidden=true;open.href='/company/workspace?lang='+encodeURIComponent(language);open.hidden=false;open.focus()}catch(error){status.textContent=error.message==='unavailable'?text[5]:text[6];if(error.message==='unavailable'){join.hidden=true;open.href='/company/workspace?lang='+encodeURIComponent(language);open.hidden=false;open.focus()}}finally{join.disabled=false}};
  if(/^[a-f0-9]{64}$/.test(token))preview();else{status.textContent=text[5];open.hidden=false}
  </script></html>`, { headers: { 'Content-Type': 'text/html; charset=utf-8', 'Cache-Control': 'no-store', 'Referrer-Policy': 'no-referrer', 'Content-Security-Policy': `default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'` } });
}
