export const recoveryWords={
 it:['Attività dei documenti','Apri registro','Altre attività','Nessuna attività registrata.','Verifica esito','Recupero completato.','L’esito resta incerto. Il documento resta protetto.','Operazione già conclusa o non recuperabile automaticamente.','Richiesta di pulizia','Cancellazione confermata','Esito incerto','Documento conservato','File presente','File non trovato','Verifica non disponibile'],
 en:['Document activity','Open activity log','More activity','No activity recorded.','Check outcome','Recovery completed.','The outcome is still uncertain. The document remains protected.','Already completed or not automatically recoverable.','Cleanup requested','Deletion confirmed','Uncertain outcome','Document retained','File present','File not found','Check unavailable'],
 de:['Dokumentenaktivität','Protokoll öffnen','Weitere Aktivitäten','Keine Aktivität erfasst.','Ergebnis prüfen','Wiederherstellung abgeschlossen.','Das Ergebnis ist noch unklar. Das Dokument bleibt geschützt.','Bereits abgeschlossen oder nicht automatisch wiederherstellbar.','Bereinigung angefordert','Löschung bestätigt','Unklares Ergebnis','Dokument behalten','Datei vorhanden','Datei nicht gefunden','Prüfung nicht verfügbar'],
 fr:['Activité des documents','Ouvrir le journal','Autres activités','Aucune activité enregistrée.','Vérifier le résultat','Récupération terminée.','Le résultat reste incertain. Le document reste protégé.','Déjà terminé ou récupération automatique impossible.','Nettoyage demandé','Suppression confirmée','Résultat incertain','Document conservé','Fichier présent','Fichier introuvable','Vérification indisponible'],
 es:['Actividad de documentos','Abrir registro','Más actividad','No hay actividad registrada.','Verificar resultado','Recuperación completada.','El resultado sigue siendo incierto. El documento sigue protegido.','Ya completado o sin recuperación automática.','Limpieza solicitada','Eliminación confirmada','Resultado incierto','Documento conservado','Archivo presente','Archivo no encontrado','Verificación no disponible'],
 nl:['Documentactiviteit','Logboek openen','Meer activiteit','Geen activiteit geregistreerd.','Uitkomst controleren','Herstel voltooid.','De uitkomst blijft onzeker. Het document blijft beschermd.','Al voltooid of niet automatisch te herstellen.','Opschoning aangevraagd','Verwijdering bevestigd','Onzekere uitkomst','Document behouden','Bestand aanwezig','Bestand niet gevonden','Controle niet beschikbaar'],
 pt:['Atividade dos documentos','Abrir registo','Mais atividades','Nenhuma atividade registada.','Verificar resultado','Recuperação concluída.','O resultado continua incerto. O documento permanece protegido.','Já concluído ou sem recuperação automática.','Limpeza solicitada','Eliminação confirmada','Resultado incerto','Documento conservado','Ficheiro presente','Ficheiro não encontrado','Verificação indisponível']
};
