import { recoveryWords } from './recovery-copy.js';
export const storageWords={
 it:['Spazio per i documenti','Torna allo spazio aziendale','Disponibile','Riservato','Capacità totale','Aggiorna','Caricamento…','Non riesco a verificare lo spazio. Riprova.','Questo controllo è riservato al titolare aziendale.','Lo spazio documenti non è ancora configurato.','Nessun allegato separato registrato.','Allegati registrati','Mostra altri','Allegato','Collegato a un resoconto','Non ancora collegato','Presente','Da verificare: file non trovato','Verifica temporaneamente non disponibile','Da verificare: dimensione diversa','Un file non collegato può essere ancora in invio. Questo controllo non cancella documenti.','La quota include gli invii interrotti. Non include database e backup.','Controllo aggiornato','Controllo completato; alcuni file richiedono una verifica.'],
 en:['Document storage','Back to company workspace','Available','Reserved','Total capacity','Refresh','Loading…','Unable to check storage. Try again.','Only the company owner can view this check.','Document storage is not configured yet.','No detached attachments registered.','Registered attachments','Show more','Attachment','Linked to a report','Not linked yet','Present','Check required: file not found','Check temporarily unavailable','Check required: size differs','An unlinked file may still be uploading. This check does not delete documents.','The quota includes interrupted uploads. Database and backups are excluded.','Check updated','Check completed; some files need attention.'],
 de:['Dokumentenspeicher','Zurück zum Unternehmensbereich','Verfügbar','Reserviert','Gesamtkapazität','Aktualisieren','Wird geladen…','Speicherprüfung nicht möglich. Erneut versuchen.','Nur der Unternehmenseigentümer kann diese Prüfung sehen.','Dokumentenspeicher noch nicht eingerichtet.','Keine separaten Belege registriert.','Registrierte Belege','Mehr anzeigen','Beleg','Mit einem Bericht verbunden','Noch nicht verbunden','Vorhanden','Prüfen: Datei nicht gefunden','Prüfung vorübergehend nicht möglich','Prüfen: abweichende Größe','Eine nicht verbundene Datei wird möglicherweise noch hochgeladen. Diese Prüfung löscht keine Dokumente.','Die Quote umfasst unterbrochene Uploads. Datenbank und Backups sind ausgeschlossen.','Prüfung aktualisiert','Prüfung abgeschlossen; einige Dateien benötigen eine Prüfung.'],
 fr:['Stockage des documents','Retour à l’espace entreprise','Disponible','Réservé','Capacité totale','Actualiser','Chargement…','Vérification impossible. Réessayez.','Ce contrôle est réservé au propriétaire de l’entreprise.','Le stockage des documents n’est pas encore configuré.','Aucune pièce jointe séparée enregistrée.','Pièces jointes enregistrées','Afficher plus','Pièce jointe','Liée à un rapport','Pas encore liée','Présente','À vérifier : fichier introuvable','Vérification temporairement indisponible','À vérifier : taille différente','Un fichier non lié peut être en cours d’envoi. Ce contrôle ne supprime aucun document.','Le quota inclut les envois interrompus. Base de données et sauvegardes exclues.','Contrôle actualisé','Contrôle terminé ; certains fichiers sont à vérifier.'],
 es:['Espacio para documentos','Volver al espacio de empresa','Disponible','Reservado','Capacidad total','Actualizar','Cargando…','No se puede verificar el espacio. Inténtalo de nuevo.','Solo el titular de la empresa puede ver este control.','El espacio de documentos aún no está configurado.','No hay adjuntos separados registrados.','Adjuntos registrados','Mostrar más','Adjunto','Vinculado a un informe','Aún sin vincular','Presente','Revisar: archivo no encontrado','Verificación temporalmente no disponible','Revisar: tamaño diferente','Un archivo sin vincular puede estar enviándose. Este control no elimina documentos.','La cuota incluye envíos interrumpidos. No incluye base de datos ni copias de seguridad.','Control actualizado','Control completado; algunos archivos necesitan revisión.'],
 nl:['Documentopslag','Terug naar bedrijfsruimte','Beschikbaar','Gereserveerd','Totale capaciteit','Vernieuwen','Laden…','Opslag niet te controleren. Probeer opnieuw.','Alleen de bedrijfseigenaar kan deze controle bekijken.','Documentopslag is nog niet ingesteld.','Geen losse bijlagen geregistreerd.','Geregistreerde bijlagen','Meer tonen','Bijlage','Gekoppeld aan een rapport','Nog niet gekoppeld','Aanwezig','Controleren: bestand niet gevonden','Controle tijdelijk niet beschikbaar','Controleren: afwijkende grootte','Een niet-gekoppeld bestand kan nog worden verstuurd. Deze controle verwijdert geen documenten.','De limiet omvat onderbroken uploads. Database en back-ups zijn uitgesloten.','Controle bijgewerkt','Controle voltooid; sommige bestanden vragen aandacht.'],
 pt:['Espaço para documentos','Voltar ao espaço empresarial','Disponível','Reservado','Capacidade total','Atualizar','A carregar…','Não foi possível verificar o espaço. Tente novamente.','Este controlo é reservado ao titular da empresa.','O espaço de documentos ainda não está configurado.','Nenhum anexo separado registado.','Anexos registados','Mostrar mais','Anexo','Associado a um relatório','Ainda não associado','Presente','Verificar: ficheiro não encontrado','Verificação temporariamente indisponível','Verificar: tamanho diferente','Um ficheiro não associado pode ainda estar a ser enviado. Este controlo não elimina documentos.','A quota inclui envios interrompidos. Base de dados e cópias de segurança excluídas.','Controlo atualizado','Controlo concluído; alguns ficheiros precisam de verificação.']
};
export function storagePage(){
 const nonce=crypto.randomUUID();
 return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Momentum</title>
 <style nonce="${nonce}">
 :root{font-family:system-ui,sans-serif;color-scheme:dark;color:#f4f2ff;background:#0c0c15}*{box-sizing:border-box}body{margin:0;padding:24px max(16px,env(safe-area-inset-right)) 32px max(16px,env(safe-area-inset-left))}main{max-width:780px;margin:auto}a{color:#cabaff;display:inline-flex;align-items:center;min-height:48px}h1{font-size:clamp(27px,5vw,38px);letter-spacing:-.03em;margin:20px 0}h2{font-size:20px}p{color:#c5c2d5;line-height:1.6}button{min-height:48px;padding:12px 20px;border:1px solid #665b80;border-radius:16px;color:inherit;background:#292239;font:inherit;cursor:pointer;transition:transform .18s,background .18s}button:active{transform:scale(.97)}button:disabled{opacity:.5;cursor:wait}a:focus-visible,button:focus-visible{outline:3px solid #c2afff;outline-offset:4px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px}.summary{border:1px solid #494056;border-radius:24px;padding:clamp(20px,4vw,32px);background:radial-gradient(at 0 0,#29223e,#15141f 75%)}.amount{display:block;font-size:clamp(30px,8vw,48px);font-variant-numeric:tabular-nums;margin:8px 0;overflow-wrap:anywhere}.stats{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:24px}.stats span,.stats strong{display:block}.stats span{color:#c5c2d5;margin-bottom:8px}.stats strong{font-variant-numeric:tabular-nums;overflow-wrap:anywhere}ul{list-style:none;padding:0}li{display:grid;grid-template-columns:1fr auto;gap:10px;padding:18px 0;border-bottom:1px solid #383348;animation:enter .2s ease-out}li p{margin:6px 0 0;font-size:14px}li strong{font-size:16px}.warning{color:#f6cf97}.status{min-height:26px}#more{width:100%;margin-top:12px}[hidden]{display:none!important}@keyframes enter{from{opacity:0;transform:translateY(4px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}@media(max-width:360px){.toolbar{align-items:flex-start;flex-direction:column}.toolbar button{width:100%}li{grid-template-columns:1fr}}
 </style><main><a id="back" href="/company/workspace"></a><p>MOMENTUM</p><div class="toolbar"><h1 id="title"></h1><button id="refresh"></button></div><p id="status" class="status" role="status" aria-live="polite"></p><section id="summary" class="summary" hidden><span id="available-label"></span><strong id="available" class="amount"></strong><div class="stats"><div><span id="reserved-label"></span><strong id="reserved"></strong></div><div><span id="total-label"></span><strong id="total"></strong></div></div><p id="scope"></p></section><section><h2 id="activity-title"></h2><button id="activity-open"></button><p id="activity-status" role="status" aria-live="polite"></p><ul id="activity-list"></ul><button id="activity-more" hidden></button></section><section id="files" hidden><h2 id="files-title"></h2><p id="safety"></p><p id="empty" hidden></p><ul id="list"></ul><button id="more" hidden></button></section></main>
 <script nonce="${nonce}">
 const words=${JSON.stringify(storageWords)},params=new URLSearchParams(location.search),language=(params.get('lang')||navigator.language||'en').split('-')[0],lang=words[language]?language:'en',t=words[lang],company=params.get('company')||'';
 document.documentElement.lang=lang;const el=id=>document.getElementById(id);for(const [id,index] of Object.entries({title:0,back:1,'available-label':2,'reserved-label':3,'total-label':4,refresh:5,'files-title':11,more:12,safety:20,scope:21,empty:10}))el(id).textContent=t[index];el('back').href='/company/workspace?lang='+encodeURIComponent(lang);
 let cursor=null,busy=false,count=0;const size=n=>new Intl.NumberFormat(lang,{maximumFractionDigits:1}).format(n/1048576)+' MiB';
 async function load(more=false){if(busy)return;busy=true;el('refresh').disabled=true;el('more').disabled=true;el('status').textContent=t[6];el('list').setAttribute('aria-busy','true');if(!more){el('summary').hidden=true;el('files').hidden=true;el('list').replaceChildren();cursor=null;count=0}
 try{if(!/^[a-zA-Z0-9_-]{1,80}$/.test(company))throw {status:403};const response=await fetch('/v1/companies/'+encodeURIComponent(company)+'/storage'+(more&&cursor?'?after='+encodeURIComponent(cursor):''),{credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(20000)});if(!response.ok){let code='';try{code=(await response.json()).error}catch{}throw {status:response.status,code}};const data=await response.json();if(data.companyId!==company||!Array.isArray(data.entries)||![data.availableBytes,data.reservedBytes,data.limitBytes].every(n=>Number.isSafeInteger(n)&&n>=0))throw Error();
 el('available').textContent=size(data.availableBytes);el('reserved').textContent=size(data.reservedBytes);el('total').textContent=size(data.limitBytes);let attention=false;
 for(const entry of data.entries){const li=document.createElement('li'),body=document.createElement('div'),heading=document.createElement('strong'),detail=document.createElement('p'),amount=document.createElement('span');heading.textContent=t[13]+' '+(++count);const statusIndex=({present:16,missing:17,unavailable:18,size_mismatch:19})[entry.object]??18;detail.textContent=t[entry.reference==='report'?14:15]+' · '+t[statusIndex];if(statusIndex!==16){detail.className='warning';attention=true}amount.textContent=size(entry.reservedBytes);body.append(heading,detail);li.append(body,amount);el('list').append(li)}
 cursor=data.nextCursor;el('more').hidden=!cursor;el('empty').hidden=count>0;el('summary').hidden=false;el('files').hidden=false;el('status').textContent=t[attention?23:22];
 }catch(error){el('status').textContent=t[[401,403].includes(error.status)?8:['storage_not_configured','not_configured'].includes(error.code)?9:7]}finally{busy=false;el('refresh').disabled=false;el('more').disabled=false;el('list').setAttribute('aria-busy','false')}}
 const recoveryWords=${JSON.stringify(recoveryWords)},r=recoveryWords[lang]||recoveryWords.en;el('activity-title').textContent=r[0];el('activity-open').textContent=r[1];el('activity-more').textContent=r[2];let activityBusy=false,activityCursor=null;
 async function activityRequest(path,body){const response=await fetch('/v1/companies/'+encodeURIComponent(company)+'/storage/'+path,{credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(20000),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});return {response,data:await response.json()}}
 async function activity(more=false){if(activityBusy)return;activityBusy=true;el('activity-open').disabled=true;el('activity-more').disabled=true;el('activity-status').textContent=t[6];if(!more){activityCursor=null;el('activity-list').replaceChildren()}
 try{const {response,data}=await activityRequest('journal'+(more&&activityCursor?'?after='+encodeURIComponent(activityCursor):''));if(!response.ok)throw Error();for(const event of data.events){const li=document.createElement('li'),description=document.createElement('div'),label=document.createElement('strong'),date=document.createElement('p');label.textContent=r[({requested:8,confirmed:9,uncertain:10,retained:11,observed_present:12,observed_missing:13,observed_unavailable:14})[event.event]??10];const timestamp=new Date(event.created_at.replace(' ','T')+'Z');date.textContent=Number.isNaN(timestamp.getTime())?'':new Intl.DateTimeFormat(lang,{dateStyle:'medium',timeStyle:'short'}).format(timestamp);description.append(label,date);li.append(description);
 if(['uncertain','observed_present','observed_missing','observed_unavailable'].includes(event.event)){const button=document.createElement('button');button.textContent=r[4];button.onclick=async()=>{if(activityBusy)return;activityBusy=true;button.disabled=true;el('activity-status').textContent=t[6];try{const result=await activityRequest('reconcile',{key:event.object_key});el('activity-status').textContent=result.response.ok?r[5]:result.data.state==='requires_review'?r[6]:result.data.error==='no_recoverable_cleanup'?r[7]:t[7];if(result.response.ok){button.dataset.done='true';button.textContent=r[5];await load()}}catch{el('activity-status').textContent=t[7]}finally{activityBusy=false;button.disabled=button.dataset.done==='true'}};li.append(button)}el('activity-list').append(li)}activityCursor=data.nextCursor;el('activity-more').hidden=!activityCursor;el('activity-status').textContent=el('activity-list').children.length?'':r[3];}catch{el('activity-status').textContent=t[7]}finally{activityBusy=false;el('activity-open').disabled=false;el('activity-more').disabled=false}}
 el('activity-open').onclick=()=>activity();el('activity-more').onclick=()=>activity(true);
 el('refresh').onclick=()=>load();el('more').onclick=()=>load(true);load();
 </script></html>`,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'`}});
}
