import { storageWords } from './storage-page.js';
const copy = {
  it: ['Il tuo spazio aziendale','Caricamento…','Nessuna azienda collegata. Apri l’invito ricevuto dal responsabile.','Invita un collaboratore','Email di lavoro','Dipendente','Responsabile','Crea invito','Copia link','Link copiato','Operazione non riuscita. Riprova.','Regole della trasferta','Giustificativo da','Per spesa','Al giorno','Nessun limite','Nessuna policy pubblicata','Apri Momentum','Altre aziende','Il link dura 7 giorni. Non inviamo email.','Trasporto','Vitto','Alloggio','Altro','Versione','Scegli un’azienda','Torna alle aziende'],
  en: ['Your company workspace','Loading…','No company connected. Open the invitation from your administrator.','Invite a colleague','Work email','Employee','Reviewer','Create invitation','Copy link','Link copied','Unable to complete. Try again.','Trip rules','Receipt required from','Per expense','Per day','No limit','No published policy','Open Momentum','More companies','The link lasts 7 days. We do not send email.','Transport','Meals','Accommodation','Other','Version','Choose a company','Back to companies'],
  de: ['Dein Unternehmensbereich','Wird geladen…','Kein Unternehmen verbunden. Öffne die Einladung deines Verantwortlichen.','Kollegen einladen','Geschäftliche E-Mail','Mitarbeiter','Verantwortlicher','Einladung erstellen','Link kopieren','Link kopiert','Vorgang fehlgeschlagen. Versuche es erneut.','Reiseregeln','Beleg erforderlich ab','Pro Ausgabe','Pro Tag','Kein Limit','Keine Richtlinie veröffentlicht','Momentum öffnen','Weitere Unternehmen','Der Link gilt 7 Tage. Wir senden keine E-Mail.','Transport','Verpflegung','Unterkunft','Sonstiges','Version','Unternehmen wählen','Zurück zu Unternehmen'],
  fr: ['Votre espace entreprise','Chargement…','Aucune entreprise liée. Ouvrez l’invitation de votre responsable.','Inviter un collègue','Email professionnel','Salarié','Responsable','Créer une invitation','Copier le lien','Lien copié','Opération impossible. Réessayez.','Règles du déplacement','Justificatif requis dès','Par dépense','Par jour','Sans plafond','Aucune règle publiée','Ouvrir Momentum','Autres entreprises','Le lien dure 7 jours. Aucun email envoyé.','Transport','Repas','Hébergement','Autre','Version','Choisir une entreprise','Retour aux entreprises'],
  es: ['Tu espacio de empresa','Cargando…','Ninguna empresa vinculada. Abre la invitación de tu responsable.','Invitar a un compañero','Email de trabajo','Empleado','Responsable','Crear invitación','Copiar enlace','Enlace copiado','No se pudo completar. Inténtalo de nuevo.','Reglas del viaje','Justificante requerido desde','Por gasto','Por día','Sin límite','Sin política publicada','Abrir Momentum','Más empresas','El enlace dura 7 días. No enviamos emails.','Transporte','Comidas','Alojamiento','Otros','Versión','Elige una empresa','Volver a empresas'],
  nl: ['Je bedrijfsruimte','Laden…','Geen bedrijf gekoppeld. Open de uitnodiging van je beheerder.','Collega uitnodigen','Zakelijke e-mail','Medewerker','Beoordelaar','Uitnodiging maken','Link kopiëren','Link gekopieerd','Niet gelukt. Probeer opnieuw.','Reisregels','Bon vereist vanaf','Per uitgave','Per dag','Geen limiet','Geen beleid gepubliceerd','Momentum openen','Meer bedrijven','De link is 7 dagen geldig. We sturen geen e-mail.','Vervoer','Maaltijden','Verblijf','Overig','Versie','Kies een bedrijf','Terug naar bedrijven'],
  pt: ['O seu espaço empresarial','A carregar…','Nenhuma empresa associada. Abra o convite do responsável.','Convidar um colega','Email de trabalho','Funcionário','Responsável','Criar convite','Copiar ligação','Ligação copiada','Não foi possível concluir. Tente novamente.','Regras da viagem','Comprovativo exigido a partir de','Por despesa','Por dia','Sem limite','Nenhuma política publicada','Abrir Momentum','Mais empresas','A ligação dura 7 dias. Não enviamos emails.','Transporte','Refeições','Alojamento','Outros','Versão','Escolha uma empresa','Voltar às empresas'],
};
export function workspacePage() {
  const nonce = crypto.randomUUID();
  return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Momentum</title>
  <style nonce="${nonce}">
  :root{font-family:system-ui,sans-serif;color-scheme:dark;background:#0c0c15;color:#f4f2ff}*{box-sizing:border-box}body{margin:0;padding:clamp(16px,4vw,40px)}main{max-width:780px;margin:auto}h1{font-size:clamp(26px,5vw,36px)}h2{font-size:22px}p{line-height:1.6;color:#c5c2d5}button,input,a{font:inherit;min-height:48px;border-radius:14px}button{padding:12px 18px;border:1px solid #4a445e;color:inherit;background:#211d33;cursor:pointer;transition:transform .15s}button:active{transform:scale(.98)}button:disabled{opacity:.55;cursor:wait}button:focus-visible,input:focus-visible,a:focus-visible{outline:3px solid #c2afff;outline-offset:3px}input{width:100%;padding:12px;border:1px solid #625979;background:#111019;color:inherit}input[type=radio]{width:22px;min-height:22px;accent-color:#b8a2ff}section{padding:clamp(18px,4vw,28px);border:1px solid #383348;border-radius:24px;margin:20px 0;background:radial-gradient(at 0 0,#252038,#15141f 70%)}#companies{display:grid;gap:12px}#companies button{text-align:left;overflow-wrap:anywhere}.primary{background:#b6a3ff;color:#171026;font-weight:700;width:100%}label{display:block;margin:14px 0 8px}fieldset{display:flex;flex-wrap:wrap;gap:16px;border:0;padding:0;margin:16px 0}fieldset label{display:flex;align-items:center;gap:8px;margin:0}legend{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.limits{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:12px}.limit{border:1px solid #41394f;border-radius:16px;padding:16px}.limit p{margin:8px 0}a{display:inline-flex;align-items:center;color:#cabaff;padding:12px 0}#status{min-height:26px}#link{margin:12px 0}[hidden]{display:none!important}@media(prefers-reduced-motion:reduce){button{transition:none}}
  </style><main><p>MOMENTUM</p><h1 id="title"></h1><p id="status" role="status" aria-live="polite"></p><div id="companies"></div><button id="more" hidden></button><section id="detail" hidden><button id="back"></button><h2 id="name"></h2><a id="new-trip" class="primary" hidden></a><a id="reports"></a><a id="storage" hidden></a><h3 id="rules-title"></h3><p id="version"></p><p id="receipt"></p><div id="limits" class="limits"></div><form id="invite" hidden><h3 id="invite-title"></h3><label id="email-label" for="email"></label><input id="email" type="email" required maxlength="254" autocomplete="email" placeholder="nome@azienda.it"><fieldset><legend id="role-label"></legend><label><input type="radio" name="role" value="employee" checked><span id="employee"></span></label><label><input type="radio" name="role" value="reviewer"><span id="reviewer"></span></label></fieldset><button id="create" class="primary"></button><p id="hint"></p><input id="link" readonly hidden><button type="button" id="copy" hidden></button></form></section><a id="open" href="/"></a></main>
  <script nonce="${nonce}">
  const storageWords=${JSON.stringify(storageWords)};const words=${JSON.stringify(copy)};const lang=(new URLSearchParams(location.search).get('lang')||navigator.language||'en').split('-')[0];const t=words[lang]||words.en;document.documentElement.lang=words[lang]?lang:'en';
  const el=id=>document.getElementById(id);for(const [id,index] of Object.entries({title:0,more:18,back:26,'rules-title':11,'invite-title':3,'email-label':4,employee:5,reviewer:6,create:7,copy:8,hint:19,open:17,'role-label':3}))el(id).textContent=t[index];el('email').placeholder='name@example.com';el('link').setAttribute('aria-label',t[8]);
  el('new-trip').textContent=({it:'Crea una trasferta',en:'Create a trip',de:'Reise erstellen',fr:'Créer un déplacement',es:'Crear un viaje',nl:'Reis maken',pt:'Criar uma viagem'})[lang]||'Create a trip';el('reports').textContent=({it:'Resoconti e approvazioni',en:'Reports and approvals',de:'Berichte und Genehmigungen',fr:'Rapports et approbations',es:'Informes y aprobaciones',nl:'Rapporten en goedkeuringen',pt:'Relat\u00f3rios e aprova\u00e7\u00f5es'})[lang]||'Reports and approvals';let cursor=null,selected=null,busy=false,generation=0;
  async function api(path,body){const response=await fetch(path,{credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(20000),...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});if(!response.ok){const error=new Error();error.status=response.status;throw error}return response.json()}
  const money=n=>n===undefined?t[15]:new Intl.NumberFormat(document.documentElement.lang,{style:'currency',currency:'EUR'}).format(n);
  async function load(){el('status').textContent=t[1];el('more').disabled=true;try{const data=await api('/v1/me/companies'+(cursor?'?after='+encodeURIComponent(cursor):''));for(const company of data.companies){const button=document.createElement('button');button.textContent=company.name;button.onclick=()=>show(company);el('companies').append(button)}cursor=data.nextCursor;el('more').hidden=!cursor;el('status').textContent=el('companies').children.length?t[25]:t[2]}catch{el('status').textContent=t[10]}finally{el('more').disabled=false}}
  async function show(company){const turn=++generation;selected=company;el('storage').hidden=company.role!=='owner';el('storage').textContent=(storageWords[lang]||storageWords.en)[0];el('storage').href='/company/storage?company='+encodeURIComponent(company.id)+'&lang='+encodeURIComponent(lang);el('reports').href='/company/reports?company='+encodeURIComponent(company.id)+'&lang='+encodeURIComponent(lang);el('new-trip').hidden=true;el('detail').hidden=false;el('companies').hidden=true;el('more').hidden=true;el('name').textContent=company.name;el('invite').hidden=true;el('link').hidden=true;el('copy').hidden=true;el('limits').replaceChildren();el('receipt').textContent='';el('version').textContent='';el('status').textContent=t[1];try{const data=await api('/v1/companies/'+encodeURIComponent(company.id)+'/policies');if(turn!==generation)return;el('new-trip').href='/?company='+encodeURIComponent(company.id)+'&lang='+encodeURIComponent(lang);el('new-trip').hidden=false;el('version').textContent=t[24]+' '+data.version;el('receipt').textContent=t[12]+' '+money(data.rules.receiptThreshold);for(const [index,category] of ['trasporto','vitto','alloggio','altro'].entries()){const card=document.createElement('div');card.className='limit';const heading=document.createElement('strong');heading.textContent=t[20+index];card.append(heading);for(const [label,values] of [[13,data.rules.expenseLimits],[14,data.rules.dailyLimits]]){const p=document.createElement('p');p.textContent=t[label]+': '+money(values?.[category]);card.append(p)}el('limits').append(card)}el('status').textContent=''}catch(error){if(turn!==generation)return;el('status').textContent=error.status===404?t[16]:t[10];if(error.status!==404)return}if(turn===generation)el('invite').hidden=company.role!=='owner'}
  el('back').onclick=()=>{generation++;selected=null;el('detail').hidden=true;el('companies').hidden=false;el('more').hidden=!cursor;el('status').textContent=t[25]};el('more').onclick=load;
  el('invite').onsubmit=async event=>{event.preventDefault();if(busy||!selected)return;busy=true;const company=selected;el('create').disabled=true;el('link').hidden=true;el('copy').hidden=true;try{const result=await api('/v1/companies/'+encodeURIComponent(company.id)+'/invitations',{email:el('email').value.trim(),role:new FormData(el('invite')).get('role')});if(selected?.id!==company.id)return;el('link').value=result.url;el('link').hidden=false;el('copy').hidden=false;el('status').textContent=t[19]}catch{el('status').textContent=t[10]}finally{busy=false;el('create').disabled=false}};
  el('copy').onclick=async()=>{try{await navigator.clipboard.writeText(el('link').value);el('status').textContent=t[9]}catch{el('link').focus();el('link').select()}};load();
  </script></html>`, { headers: { 'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'` } });
}
