import { storageWords } from './storage-page.js';
const copy = {
  it: ['Il tuo spazio aziendale','Caricamento…','Nessuna azienda collegata. Apri l’invito ricevuto dal responsabile.','Invita un collaboratore','Email di lavoro','Dipendente','Responsabile','Crea invito','Copia link','Link copiato','Operazione non riuscita. Riprova.','Regole della trasferta','Giustificativo da','Per spesa','Al giorno','Nessun limite','Nessuna policy pubblicata','Apri Momentum','Altre aziende','Il link dura 7 giorni. Non inviamo email.','Trasporto','Vitto','Alloggio','Altro','Versione','Scegli un’azienda','Torna alle aziende','Modifica policy','Diaria (opzionale)','Quota piena/giorno','Quota ridotta (primo/ultimo giorno)','Rimborso chilometrico (opzionale)','Tariffa','Unità','Salva policy','Policy salvata','Un altro editor ha pubblicato nel frattempo — ricaricato, controlla e riprova','Soglia scontrino'],
  en: ['Your company workspace','Loading…','No company connected. Open the invitation from your administrator.','Invite a colleague','Work email','Employee','Reviewer','Create invitation','Copy link','Link copied','Unable to complete. Try again.','Trip rules','Receipt required from','Per expense','Per day','No limit','No published policy','Open Momentum','More companies','The link lasts 7 days. We do not send email.','Transport','Meals','Accommodation','Other','Version','Choose a company','Back to companies','Edit policy','Per diem (optional)','Full rate/day','Reduced rate (first/last day)','Mileage reimbursement (optional)','Rate','Unit','Save policy','Policy saved','Another editor published in the meantime — reloaded, check and retry','Receipt threshold'],
  de: ['Dein Unternehmensbereich','Wird geladen…','Kein Unternehmen verbunden. Öffne die Einladung deines Verantwortlichen.','Kollegen einladen','Geschäftliche E-Mail','Mitarbeiter','Verantwortlicher','Einladung erstellen','Link kopieren','Link kopiert','Vorgang fehlgeschlagen. Versuche es erneut.','Reiseregeln','Beleg erforderlich ab','Pro Ausgabe','Pro Tag','Kein Limit','Keine Richtlinie veröffentlicht','Momentum öffnen','Weitere Unternehmen','Der Link gilt 7 Tage. Wir senden keine E-Mail.','Transport','Verpflegung','Unterkunft','Sonstiges','Version','Unternehmen wählen','Zurück zu Unternehmen','Richtlinie bearbeiten','Verpflegungspauschale (optional)','Voller Satz/Tag','Reduzierter Satz (erster/letzter Tag)','Kilometerpauschale (optional)','Satz','Einheit','Richtlinie speichern','Richtlinie gespeichert','Ein anderer Bearbeiter hat inzwischen veröffentlicht — neu geladen, prüfen und erneut versuchen','Beleggrenze'],
  fr: ['Votre espace entreprise','Chargement…','Aucune entreprise liée. Ouvrez l’invitation de votre responsable.','Inviter un collègue','Email professionnel','Salarié','Responsable','Créer une invitation','Copier le lien','Lien copié','Opération impossible. Réessayez.','Règles du déplacement','Justificatif requis dès','Par dépense','Par jour','Sans plafond','Aucune règle publiée','Ouvrir Momentum','Autres entreprises','Le lien dure 7 jours. Aucun email envoyé.','Transport','Repas','Hébergement','Autre','Version','Choisir une entreprise','Retour aux entreprises','Modifier la politique','Indemnité journalière (facultatif)','Taux plein/jour','Taux réduit (premier/dernier jour)','Remboursement kilométrique (facultatif)','Taux','Unité','Enregistrer la politique','Politique enregistrée','Un autre éditeur a publié en attendant — rechargé, vérifiez et réessayez','Seuil du justificatif'],
  es: ['Tu espacio de empresa','Cargando…','Ninguna empresa vinculada. Abre la invitación de tu responsable.','Invitar a un compañero','Email de trabajo','Empleado','Responsable','Crear invitación','Copiar enlace','Enlace copiado','No se pudo completar. Inténtalo de nuevo.','Reglas del viaje','Justificante requerido desde','Por gasto','Por día','Sin límite','Sin política publicada','Abrir Momentum','Más empresas','El enlace dura 7 días. No enviamos emails.','Transporte','Comidas','Alojamiento','Otros','Versión','Elige una empresa','Volver a empresas','Editar política','Dieta (opcional)','Cuota completa/día','Cuota reducida (primer/último día)','Reembolso por kilometraje (opcional)','Tarifa','Unidad','Guardar política','Política guardada','Otro editor publicó mientras tanto — recargado, comprueba y vuelve a intentarlo','Umbral de justificante'],
  nl: ['Je bedrijfsruimte','Laden…','Geen bedrijf gekoppeld. Open de uitnodiging van je beheerder.','Collega uitnodigen','Zakelijke e-mail','Medewerker','Beoordelaar','Uitnodiging maken','Link kopiëren','Link gekopieerd','Niet gelukt. Probeer opnieuw.','Reisregels','Bon vereist vanaf','Per uitgave','Per dag','Geen limiet','Geen beleid gepubliceerd','Momentum openen','Meer bedrijven','De link is 7 dagen geldig. We sturen geen e-mail.','Vervoer','Maaltijden','Verblijf','Overig','Versie','Kies een bedrijf','Terug naar bedrijven','Beleid bewerken','Dagvergoeding (optioneel)','Volledig tarief/dag','Verlaagd tarief (eerste/laatste dag)','Kilometervergoeding (optioneel)','Tarief','Eenheid','Beleid opslaan','Beleid opgeslagen','Een andere editor heeft ondertussen gepubliceerd — opnieuw geladen, controleer en probeer opnieuw','Bongrens'],
  pt: ['O seu espaço empresarial','A carregar…','Nenhuma empresa associada. Abra o convite do responsável.','Convidar um colega','Email de trabalho','Funcionário','Responsável','Criar convite','Copiar ligação','Ligação copiada','Não foi possível concluir. Tente novamente.','Regras da viagem','Comprovativo exigido a partir de','Por despesa','Por dia','Sem limite','Nenhuma política publicada','Abrir Momentum','Mais empresas','A ligação dura 7 dias. Não enviamos emails.','Transporte','Refeições','Alojamento','Outros','Versão','Escolha uma empresa','Voltar às empresas','Editar política','Diária (opcional)','Quota cheia/dia','Quota reduzida (primeiro/último dia)','Reembolso por quilometragem (opcional)','Taxa','Unidade','Guardar política','Política guardada','Outro editor publicou entretanto — recarregado, verifica e tenta novamente','Limite de comprovativo'],
};
export function workspacePage() {
  const nonce = crypto.randomUUID();
  return new Response(`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Momentum</title>
  <style nonce="${nonce}">
  :root{font-family:system-ui,sans-serif;color-scheme:dark;background:#0c0c15;color:#f4f2ff}*{box-sizing:border-box}body{margin:0;padding:clamp(16px,4vw,40px)}main{max-width:780px;margin:auto}h1{font-size:clamp(26px,5vw,36px)}h2{font-size:22px}h3{font-size:18px;margin-top:28px}h4{font-size:15px;margin:20px 0 4px}p{line-height:1.6;color:#c5c2d5}button,input,a,select{font:inherit;min-height:48px;border-radius:14px}button{padding:12px 18px;border:1px solid #4a445e;color:inherit;background:#211d33;cursor:pointer;transition:transform .15s}button:active{transform:scale(.98)}button:disabled{opacity:.55;cursor:wait}button:focus-visible,input:focus-visible,a:focus-visible,select:focus-visible{outline:3px solid #c2afff;outline-offset:3px}input,select{width:100%;padding:12px;border:1px solid #625979;background:#111019;color:inherit}input[type=radio]{width:22px;min-height:22px;accent-color:#b8a2ff}section{padding:clamp(18px,4vw,28px);border:1px solid #383348;border-radius:24px;margin:20px 0;background:radial-gradient(at 0 0,#252038,#15141f 70%)}#companies{display:grid;gap:12px}#companies button{text-align:left;overflow-wrap:anywhere}.primary{background:#b6a3ff;color:#171026;font-weight:700;width:100%}label{display:block;margin:14px 0 8px}fieldset{display:flex;flex-wrap:wrap;gap:16px;border:0;padding:0;margin:16px 0}fieldset label{display:flex;align-items:center;gap:8px;margin:0}legend{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}.limits{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,220px),1fr));gap:12px}.limit{border:1px solid #41394f;border-radius:16px;padding:16px}.limit p{margin:8px 0}.limit label{margin:10px 0 4px;font-size:13px;color:#c5c2d5}a{display:inline-flex;align-items:center;color:#cabaff;padding:12px 0}#status{min-height:26px}#link{margin:12px 0}[hidden]{display:none!important}@media(prefers-reduced-motion:reduce){button{transition:none}}
  </style><main><p>MOMENTUM</p><h1 id="title"></h1><p id="status" role="status" aria-live="polite"></p><div id="companies"></div><button id="more" hidden></button><section id="detail" hidden><button id="back"></button><h2 id="name"></h2><a id="new-trip" class="primary" hidden></a><a id="reports"></a><a id="storage" hidden></a><h3 id="rules-title"></h3><p id="version"></p><p id="receipt"></p><div id="limits" class="limits"></div>
  <form id="edit-policy" hidden><h3 id="edit-title"></h3>
    <label id="receipt-edit-label" for="receipt-input"></label><input id="receipt-input" type="number" step="0.01" min="0" required>
    <div id="limits-edit" class="limits"></div>
    <h4 id="perdiem-title"></h4>
    <label id="perdiem-full-label" for="perdiem-full"></label><input id="perdiem-full" type="number" step="0.01" min="0">
    <label id="perdiem-reduced-label" for="perdiem-reduced"></label><input id="perdiem-reduced" type="number" step="0.01" min="0">
    <h4 id="mileage-title"></h4>
    <label id="mileage-rate-label" for="mileage-rate"></label><input id="mileage-rate" type="number" step="0.001" min="0">
    <label id="mileage-unit-label" for="mileage-unit"></label><select id="mileage-unit"><option value="km">km</option><option value="mi">mi</option></select>
    <button id="save-policy" class="primary" type="submit"></button>
  </form>
  <form id="invite" hidden><h3 id="invite-title"></h3><label id="email-label" for="email"></label><input id="email" type="email" required maxlength="254" autocomplete="email" placeholder="nome@azienda.it"><fieldset><legend id="role-label"></legend><label><input type="radio" name="role" value="employee" checked><span id="employee"></span></label><label><input type="radio" name="role" value="reviewer"><span id="reviewer"></span></label></fieldset><button id="create" class="primary"></button><p id="hint"></p><input id="link" readonly hidden><button type="button" id="copy" hidden></button></form></section><a id="open" href="/"></a></main>
  <script nonce="${nonce}">
  const storageWords=${JSON.stringify(storageWords)};const words=${JSON.stringify(copy)};const lang=(new URLSearchParams(location.search).get('lang')||navigator.language||'en').split('-')[0];const t=words[lang]||words.en;document.documentElement.lang=words[lang]?lang:'en';
  const el=id=>document.getElementById(id);for(const [id,index] of Object.entries({title:0,more:18,back:26,'rules-title':11,'invite-title':3,'email-label':4,employee:5,reviewer:6,create:7,copy:8,hint:19,open:17,'role-label':3,'edit-title':27,'perdiem-title':28,'perdiem-full-label':29,'perdiem-reduced-label':30,'mileage-title':31,'mileage-rate-label':32,'mileage-unit-label':33,'save-policy':34,'receipt-edit-label':37}))el(id).textContent=t[index];el('email').placeholder='name@example.com';el('link').setAttribute('aria-label',t[8]);
  el('new-trip').textContent=({it:'Crea una trasferta',en:'Create a trip',de:'Reise erstellen',fr:'Créer un déplacement',es:'Crear un viaje',nl:'Reis maken',pt:'Criar uma viagem'})[lang]||'Create a trip';el('reports').textContent=({it:'Resoconti e approvazioni',en:'Reports and approvals',de:'Berichte und Genehmigungen',fr:'Rapports et approbations',es:'Informes y aprobaciones',nl:'Rapporten en goedkeuringen',pt:'Relatórios e aprovações'})[lang]||'Reports and approvals';let cursor=null,selected=null,busy=false,generation=0,policyVersion=0;
  async function api(path,body,headers){const response=await fetch(path,{credentials:'same-origin',redirect:'error',signal:AbortSignal.timeout(20000),...(body?{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(body)}:{})});if(!response.ok){const error=new Error();error.status=response.status;throw error}return response.json()}
  const money=n=>n===undefined?t[15]:new Intl.NumberFormat(document.documentElement.lang,{style:'currency',currency:'EUR'}).format(n);
  async function load(){el('status').textContent=t[1];el('more').disabled=true;try{const data=await api('/v1/me/companies'+(cursor?'?after='+encodeURIComponent(cursor):''));for(const company of data.companies){const button=document.createElement('button');button.textContent=company.name;button.onclick=()=>show(company);el('companies').append(button)}cursor=data.nextCursor;el('more').hidden=!cursor;el('status').textContent=el('companies').children.length?t[25]:t[2]}catch{el('status').textContent=t[10]}finally{el('more').disabled=false}}
  // Chi può pubblicare (owner/policy_admin, stesso controllo del server in
  // worker.js validateCompanyRules/companyRequest — qui è solo UX, la vera
  // porta resta il controllo server-side, mai fidarsi solo del client).
  function puoModificare(company){return company.role==='owner'||company.role==='policy_admin'}
  function riempiFormLimiti(rules){el('limits-edit').replaceChildren();for(const [index,category] of ['trasporto','vitto','alloggio','altro'].entries()){const card=document.createElement('div');card.className='limit';const heading=document.createElement('strong');heading.textContent=t[20+index];card.append(heading);for(const [labelIndex,key,values] of [[13,'expense',rules?.expenseLimits],[14,'daily',rules?.dailyLimits]]){const label=document.createElement('label');label.htmlFor='limit-'+key+'-'+category;label.textContent=t[labelIndex];const input=document.createElement('input');input.id='limit-'+key+'-'+category;input.type='number';input.step='0.01';input.min='0';input.value=values?.[category]??'';card.append(label,input)}el('limits-edit').append(card)}}
  function riempiFormPolicy(rules){el('receipt-input').value=rules?.receiptThreshold??'';riempiFormLimiti(rules);el('perdiem-full').value=rules?.perDiem?.piena??'';el('perdiem-reduced').value=rules?.perDiem?.ridotta??'';el('mileage-rate').value=rules?.mileage?.tariffa??'';el('mileage-unit').value=rules?.mileage?.unita||'km'}
  async function show(company){const turn=++generation;selected=company;el('storage').hidden=company.role!=='owner';el('storage').textContent=(storageWords[lang]||storageWords.en)[0];el('storage').href='/company/storage?company='+encodeURIComponent(company.id)+'&lang='+encodeURIComponent(lang);el('reports').href='/company/reports?company='+encodeURIComponent(company.id)+'&lang='+encodeURIComponent(lang);el('new-trip').hidden=true;el('detail').hidden=false;el('companies').hidden=true;el('more').hidden=true;el('name').textContent=company.name;el('invite').hidden=true;el('link').hidden=true;el('copy').hidden=true;el('limits').replaceChildren();el('receipt').textContent='';el('version').textContent='';el('edit-policy').hidden=true;el('status').textContent=t[1];policyVersion=0;try{const data=await api('/v1/companies/'+encodeURIComponent(company.id)+'/policies');if(turn!==generation)return;policyVersion=data.version;el('new-trip').href='/?company='+encodeURIComponent(company.id)+'&lang='+encodeURIComponent(lang);el('new-trip').hidden=false;el('version').textContent=t[24]+' '+data.version;el('receipt').textContent=t[12]+' '+money(data.rules.receiptThreshold);for(const [index,category] of ['trasporto','vitto','alloggio','altro'].entries()){const card=document.createElement('div');card.className='limit';const heading=document.createElement('strong');heading.textContent=t[20+index];card.append(heading);for(const [label,values] of [[13,data.rules.expenseLimits],[14,data.rules.dailyLimits]]){const p=document.createElement('p');p.textContent=t[label]+': '+money(values?.[category]);card.append(p)}el('limits').append(card)}if(puoModificare(company)){riempiFormPolicy(data.rules);el('edit-policy').hidden=false}el('status').textContent=''}catch(error){if(turn!==generation)return;el('status').textContent=error.status===404?t[16]:t[10];if(error.status===404&&puoModificare(company)){riempiFormPolicy(null);el('edit-policy').hidden=false}if(error.status!==404)return}if(turn===generation)el('invite').hidden=company.role!=='owner'}
  el('back').onclick=()=>{generation++;selected=null;el('detail').hidden=true;el('companies').hidden=false;el('more').hidden=!cursor;el('status').textContent=t[25]};el('more').onclick=load;
  el('invite').onsubmit=async event=>{event.preventDefault();if(busy||!selected)return;busy=true;const company=selected;el('create').disabled=true;el('link').hidden=true;el('copy').hidden=true;try{const result=await api('/v1/companies/'+encodeURIComponent(company.id)+'/invitations',{email:el('email').value.trim(),role:new FormData(el('invite')).get('role')});if(selected?.id!==company.id)return;el('link').value=result.url;el('link').hidden=false;el('copy').hidden=false;el('status').textContent=t[19]}catch{el('status').textContent=t[10]}finally{busy=false;el('create').disabled=false}};
  el('copy').onclick=async()=>{try{await navigator.clipboard.writeText(el('link').value);el('status').textContent=t[9]}catch{el('link').focus();el('link').select()}};
  // Pubblica la policy: SEMPRE l'insieme intero delle regole (il server
  // sostituisce, non fa merge) — un campo lasciato vuoto sparisce (nessun
  // limite/nessuna diaria/nessun chilometraggio), mai un valore vecchio
  // che resta silenziosamente agganciato a un campo che l'utente ha svuotato.
  function numeroOVuoto(id){const v=parseFloat(el(id).value);return Number.isFinite(v)&&v>0?v:(el(id).value===''?null:v)}
  el('edit-policy').onsubmit=async event=>{event.preventDefault();if(busy||!selected||!puoModificare(selected))return;busy=true;const company=selected;el('save-policy').disabled=true;try{
    const receiptThreshold=parseFloat(el('receipt-input').value);
    if(!Number.isFinite(receiptThreshold)||receiptThreshold<0)throw new Error('invalid');
    const expenseLimits={},dailyLimits={};
    for(const category of ['trasporto','vitto','alloggio','altro']){
      const e=numeroOVuoto('limit-expense-'+category);if(e!=null&&e>0)expenseLimits[category]=e;
      const d=numeroOVuoto('limit-daily-'+category);if(d!=null&&d>0)dailyLimits[category]=d;
    }
    const rules={currency:'EUR',receiptThreshold,expenseLimits,dailyLimits};
    const piena=parseFloat(el('perdiem-full').value),ridotta=parseFloat(el('perdiem-reduced').value);
    if(Number.isFinite(piena)&&Number.isFinite(ridotta)&&piena>0)rules.perDiem={piena,ridotta};
    const tariffa=parseFloat(el('mileage-rate').value);
    if(Number.isFinite(tariffa)&&tariffa>0)rules.mileage={tariffa,unita:el('mileage-unit').value};
    const result=await api('/v1/companies/'+encodeURIComponent(company.id)+'/policies',rules,{'If-Match':'"'+policyVersion+'"'});
    if(selected?.id!==company.id)return;policyVersion=result.version;el('status').textContent=t[35];show(company);
  }catch(error){if(selected?.id!==company.id)return;el('status').textContent=error?.status===409?t[36]:t[10];if(error?.status===409)show(company)}finally{busy=false;el('save-policy').disabled=false}};
  load();
  </script></html>`, { headers: { 'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':`default-src 'none'; script-src 'nonce-${nonce}'; style-src 'nonce-${nonce}'; connect-src 'self'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'` } });
}
